import type { CoachPlan, Exercise, MuscleGroup } from './types';

const sourceUrl = 'https://www.bilibili.com/video/BV1FcdZBNEm3/';
const dayOneSourceUrl = 'https://www.bilibili.com/video/BV1CSoKBaEgK/';
const dayTwoSourceUrl = 'https://www.bilibili.com/video/BV1v5opBhEDc/';
const dayThreeSourceUrl = 'https://www.bilibili.com/video/BV17aovBqEdg/';

export const exercises: Exercise[] = [
  {
    id: 'barbell-bench-press',
    name: '杠铃卧推',
    muscleGroups: ['胸', '三头', '肩'],
    equipment: '杠铃',
    cues: ['肩胛后收下沉', '下放到胸部附近', '推起时保持手腕中立'],
    commonMistakes: ['臀部离凳', '手腕过度后折', '下放路径过高'],
    planFit: ['Day 1'],
  },
  {
    id: 'incline-dumbbell-press',
    name: '上斜哑铃卧推',
    muscleGroups: ['胸', '肩', '三头'],
    equipment: '哑铃',
    cues: ['凳面保持上斜', '肘部略低于肩', '顶端不猛烈碰撞哑铃'],
    commonMistakes: ['斜度过高变成肩推', '下放过浅', '耸肩发力'],
    planFit: ['Day 1'],
  },
  {
    id: 'dumbbell-fly',
    name: '哑铃飞鸟',
    muscleGroups: ['胸'],
    equipment: '哑铃',
    cues: ['肘部微屈固定', '胸肌拉伸后夹回', '动作节奏放慢'],
    commonMistakes: ['手臂完全伸直', '重量过大', '变成推举'],
    planFit: ['Day 1'],
  },
  {
    id: 'cable-crossover',
    name: '绳索夹胸',
    muscleGroups: ['胸'],
    equipment: '龙门架',
    cues: ['身体微前倾', '手臂弧线向内夹', '顶端收缩胸肌'],
    commonMistakes: ['借助身体摆动', '耸肩', '只用手臂拉'],
    planFit: ['Day 1'],
  },
  {
    id: 'push-up',
    name: '俯卧撑',
    muscleGroups: ['胸', '三头', '核心'],
    equipment: '自重',
    cues: ['身体成直线', '胸部主动靠近地面', '推起时核心收紧'],
    commonMistakes: ['塌腰', '半程动作', '肘部完全外展'],
    planFit: ['Day 1'],
  },
  {
    id: 'overhead-press',
    name: '杠铃推举',
    muscleGroups: ['肩', '三头'],
    equipment: '杠铃',
    cues: ['核心收紧', '杠铃贴近面部上行', '顶端稳定锁定'],
    commonMistakes: ['腰椎过度后仰', '杠铃路径太远', '借腿过多'],
    planFit: ['Day 1'],
  },
  {
    id: 'dumbbell-shoulder-press',
    name: '哑铃肩推',
    muscleGroups: ['肩', '三头'],
    equipment: '哑铃',
    cues: ['前臂接近垂直', '推起不过度撞击', '下放到可控深度'],
    commonMistakes: ['耸肩', '手腕不稳', '下放过快'],
    planFit: ['Day 1'],
  },
  {
    id: 'lateral-raise',
    name: '哑铃侧平举',
    muscleGroups: ['肩'],
    equipment: '哑铃',
    cues: ['肘部带动上抬', '停在肩高附近', '保持躯干稳定'],
    commonMistakes: ['甩动借力', '耸肩', '手腕高于肘部过多'],
    planFit: ['Day 1'],
  },
  {
    id: 'cable-lateral-raise',
    name: '绳索侧平举',
    muscleGroups: ['肩'],
    equipment: '龙门架',
    cues: ['站位让阻力持续', '小臂放松', '顶端短暂停顿'],
    commonMistakes: ['身体大幅摆动', '重量过大', '斜方肌代偿'],
    planFit: ['Day 1'],
  },
  {
    id: 'triceps-pushdown',
    name: '绳索下压',
    muscleGroups: ['三头'],
    equipment: '绳索',
    cues: ['夹紧大臂', '肘关节固定', '底端充分伸肘'],
    commonMistakes: ['肩膀参与下压', '身体前后晃', '半程动作'],
    planFit: ['Day 1'],
  },
  {
    id: 'skull-crusher',
    name: '仰卧臂屈伸',
    muscleGroups: ['三头'],
    equipment: '杠铃',
    cues: ['大臂略向后倾', '控制下放到额头后侧', '伸肘发力'],
    commonMistakes: ['肘部外开', '下放砸向额头', '肩关节移动过多'],
    planFit: ['Day 1'],
  },
  {
    id: 'parallel-bar-dip',
    name: '双杠臂屈伸',
    muscleGroups: ['胸', '三头', '肩'],
    equipment: '双杠',
    cues: ['身体略前倾', '肩胛保持稳定', '推起时用胸和三头协同发力'],
    commonMistakes: ['下放失控', '肩膀顶到耳朵', '肘部完全外翻'],
    planFit: ['Day 1'],
  },
  {
    id: 'y-raise',
    name: 'Y 字侧平举',
    muscleGroups: ['肩'],
    equipment: '哑铃',
    cues: ['手臂沿斜前方抬起', '小重量控制轨迹', '顶端感受肩部发力'],
    commonMistakes: ['重量过大甩动', '耸肩代偿', '抬成正前平举'],
    planFit: ['Day 1'],
  },
  {
    id: 'close-grip-bench',
    name: '窄握卧推',
    muscleGroups: ['三头', '胸'],
    equipment: '杠铃',
    cues: ['握距略窄于卧推', '肘部贴近身体', '稳定下放'],
    commonMistakes: ['握距过窄压手腕', '肘部乱晃', '借胸过多'],
    planFit: ['Day 1'],
  },
  {
    id: 'pull-up',
    name: '引体向上',
    muscleGroups: ['背', '二头'],
    equipment: '单杠',
    cues: ['先下沉肩胛', '胸部靠近杠', '控制下放'],
    commonMistakes: ['只用手臂拉', '摆动借力', '下放不完整'],
    planFit: ['Day 2'],
  },
  {
    id: 'lat-pulldown',
    name: '高位下拉',
    muscleGroups: ['背', '二头'],
    equipment: '器械',
    cues: ['胸口上挺', '肘部向下向后', '拉到锁骨附近'],
    commonMistakes: ['身体后仰过多', '耸肩', '用手腕硬拉'],
    planFit: ['Day 2'],
  },
  {
    id: 'barbell-row',
    name: '杠铃划船',
    muscleGroups: ['背', '二头'],
    equipment: '杠铃',
    cues: ['髋部折叠', '背部保持中立', '肘部向后拉'],
    commonMistakes: ['腰背弯曲', '身体起伏太大', '拉到胸前过高'],
    planFit: ['Day 2'],
  },
  {
    id: 'seated-cable-row',
    name: '坐姿绳索划船',
    muscleGroups: ['背', '二头'],
    equipment: '绳索',
    cues: ['躯干稳定', '肩胛后收', '手柄拉向腹部'],
    commonMistakes: ['前后大幅晃动', '耸肩', '手臂先疲劳'],
    planFit: ['Day 2'],
  },
  {
    id: 'one-arm-dumbbell-row',
    name: '单臂哑铃划船',
    muscleGroups: ['背'],
    equipment: '哑铃',
    cues: ['支撑侧稳定', '肘部贴身体向后', '顶端挤压背部'],
    commonMistakes: ['转体过大', '耸肩', '只做半程'],
    planFit: ['Day 2'],
  },
  {
    id: 'straight-arm-pulldown',
    name: '直臂下压',
    muscleGroups: ['背'],
    equipment: '绳索',
    cues: ['手臂微屈固定', '肩关节带动下压', '感受背阔肌收缩'],
    commonMistakes: ['变成三头下压', '耸肩', '身体摇摆'],
    planFit: ['Day 2'],
  },
  {
    id: 'face-pull',
    name: '面拉',
    muscleGroups: ['肩', '背'],
    equipment: '绳索',
    cues: ['拉向面部', '肘部打开', '顶端外旋'],
    commonMistakes: ['重量过大', '下背代偿', '拉得太低'],
    planFit: ['Day 2'],
  },
  {
    id: 'rear-delt-fly',
    name: '俯身反向飞鸟',
    muscleGroups: ['肩', '背'],
    equipment: '哑铃',
    cues: ['髋部折叠', '肘部微屈', '后束带动外展'],
    commonMistakes: ['斜方肌代偿', '甩动借力', '手臂过度伸直'],
    planFit: ['Day 2'],
  },
  {
    id: 'barbell-curl',
    name: '杠铃弯举',
    muscleGroups: ['二头'],
    equipment: '杠铃',
    cues: ['大臂贴近身体', '控制离心下放', '顶端收缩二头'],
    commonMistakes: ['身体后仰借力', '肘部前移过多', '下放不完全'],
    planFit: ['Day 2'],
  },
  {
    id: 'dumbbell-curl',
    name: '哑铃弯举',
    muscleGroups: ['二头'],
    equipment: '哑铃',
    cues: ['掌心逐渐向上', '两侧节奏一致', '保持肩部放松'],
    commonMistakes: ['甩动', '耸肩', '只做上半程'],
    planFit: ['Day 2'],
  },
  {
    id: 'hammer-curl',
    name: '锤式弯举',
    muscleGroups: ['二头'],
    equipment: '哑铃',
    cues: ['掌心相对', '手腕中立', '控制重量下放'],
    commonMistakes: ['肘部乱晃', '耸肩', '速度过快'],
    planFit: ['Day 2'],
  },
  {
    id: 'squat',
    name: '杠铃深蹲',
    muscleGroups: ['腿', '臀', '核心'],
    equipment: '杠铃',
    cues: ['脚掌稳固', '膝盖跟随脚尖', '躯干保持张力'],
    commonMistakes: ['膝盖内扣', '塌腰', '重心前移'],
    planFit: ['Day 3'],
  },
  {
    id: 'front-squat',
    name: '前蹲',
    muscleGroups: ['腿', '核心'],
    equipment: '杠铃',
    cues: ['肘部抬高', '躯干更直立', '下蹲保持核心收紧'],
    commonMistakes: ['肘部下掉', '上背松', '脚跟离地'],
    planFit: ['Day 3'],
  },
  {
    id: 'leg-press',
    name: '腿举',
    muscleGroups: ['腿', '臀'],
    equipment: '器械',
    cues: ['腰背贴住靠垫', '膝盖沿脚尖方向', '控制下放深度'],
    commonMistakes: ['臀部卷离靠垫', '膝盖内扣', '锁死膝盖'],
    planFit: ['Day 3'],
  },
  {
    id: 'romanian-deadlift',
    name: '罗马尼亚硬拉',
    muscleGroups: ['腿', '臀', '背'],
    equipment: '杠铃',
    cues: ['髋部向后推', '杠铃贴近腿', '感受腘绳肌拉伸'],
    commonMistakes: ['膝盖弯曲过多', '腰背弯曲', '杠铃远离身体'],
    planFit: ['Day 3'],
  },
  {
    id: 'deadlift',
    name: '传统硬拉',
    muscleGroups: ['全身', '背', '腿', '臀'],
    equipment: '杠铃',
    cues: ['杠铃贴近小腿', '背部保持中立', '腿和髋协同发力'],
    commonMistakes: ['起拉时弓背', '臀部先抬', '杠铃绕膝'],
    planFit: ['Day 3'],
  },
  {
    id: 'leg-extension',
    name: '腿屈伸',
    muscleGroups: ['腿'],
    equipment: '器械',
    cues: ['膝关节对准轴心', '顶端收缩股四头肌', '慢速下放'],
    commonMistakes: ['重量过大甩动', '坐姿不稳', '底部放松过久'],
    planFit: ['Day 3'],
  },
  {
    id: 'leg-curl',
    name: '腿弯举',
    muscleGroups: ['腿'],
    equipment: '器械',
    cues: ['髋部贴稳垫子', '脚跟向臀部卷', '控制离心'],
    commonMistakes: ['臀部抬起', '借惯性', '动作幅度太短'],
    planFit: ['Day 3'],
  },
  {
    id: 'walking-lunge',
    name: '行走弓步',
    muscleGroups: ['腿', '臀'],
    equipment: '哑铃',
    cues: ['步幅稳定', '前脚全脚掌发力', '躯干保持直立'],
    commonMistakes: ['膝盖内扣', '身体左右晃', '步幅忽大忽小'],
    planFit: ['Day 3'],
  },
  {
    id: 'bulgarian-split-squat',
    name: '保加利亚分腿蹲',
    muscleGroups: ['腿', '臀'],
    equipment: '哑铃',
    cues: ['前脚站稳', '后脚只辅助平衡', '下放到可控深度'],
    commonMistakes: ['身体前扑', '前膝内扣', '左右差异过大'],
    planFit: ['Day 3'],
  },
  {
    id: 'hip-thrust',
    name: '臀推',
    muscleGroups: ['臀', '腿'],
    equipment: '杠铃',
    cues: ['上背支撑稳定', '顶端骨盆后倾', '用臀部推起'],
    commonMistakes: ['腰部代偿', '脚距不合适', '顶端过度挺腰'],
    planFit: ['Day 3'],
  },
  {
    id: 'standing-calf-raise',
    name: '站姿提踵',
    muscleGroups: ['腿'],
    equipment: '器械',
    cues: ['脚跟充分下放', '顶端踮高停顿', '膝盖保持稳定'],
    commonMistakes: ['弹震借力', '幅度太短', '脚踝内外翻'],
    planFit: ['Day 3'],
  },
  {
    id: 'plank',
    name: '平板支撑',
    muscleGroups: ['核心'],
    equipment: '自重',
    cues: ['肋骨下沉', '臀腹同时收紧', '身体保持直线'],
    commonMistakes: ['塌腰', '臀部过高', '憋气'],
    planFit: ['辅助'],
  },
  {
    id: 'hanging-leg-raise',
    name: '悬垂举腿',
    muscleGroups: ['核心'],
    equipment: '单杠',
    cues: ['骨盆后倾卷起', '控制下放', '减少身体摆动'],
    commonMistakes: ['甩腿', '只抬髋不卷腹', '握力先耗尽'],
    planFit: ['辅助'],
  },
  {
    id: 'cable-crunch',
    name: '绳索卷腹',
    muscleGroups: ['核心'],
    equipment: '绳索',
    cues: ['脊柱逐节卷曲', '骨盆稳定', '腹部主动收缩'],
    commonMistakes: ['髋部折叠代偿', '手臂拉绳', '重量过大'],
    planFit: ['辅助'],
  },
  {
    id: 'farmer-carry',
    name: '农夫行走',
    muscleGroups: ['全身', '核心'],
    equipment: '哑铃',
    cues: ['身体站高', '肩胛稳定', '步伐均匀'],
    commonMistakes: ['身体歪斜', '耸肩', '走得过快失控'],
    planFit: ['辅助'],
  },
  {
    id: 'kettlebell-swing',
    name: '壶铃摆荡',
    muscleGroups: ['臀', '腿', '核心'],
    equipment: '壶铃',
    cues: ['髋部主导', '手臂像绳子', '顶端臀部收紧'],
    commonMistakes: ['蹲起代替髋伸', '用肩抬壶铃', '腰背松散'],
    planFit: ['辅助'],
  },
  {
    id: 'ab-wheel-rollout',
    name: '健腹轮',
    muscleGroups: ['核心'],
    equipment: '健腹轮',
    cues: ['骨盆后倾', '向前推出到可控距离', '用腹部把身体拉回'],
    commonMistakes: ['塌腰', '推出过远失控', '只用手臂拉回'],
    planFit: ['辅助'],
  },
];

export const coachPlans: CoachPlan[] = [
  {
    id: 'kaishengwang-tanchengyi-three-day-split',
    coachName: '凯圣王-谭成义',
    title: '三分化训练计划',
    description: '以胸肩三头、背后束二头、腿部三天为骨架的力量训练跟练计划。动作要点根据 B 站跟练视频音轨转写整理，并保留原视频入口。',
    sourceUrl,
    planType: 'builtin',
    days: [
      {
        id: 'day-1-push',
        name: 'Day 1 胸 / 肩 / 三头',
        focus: ['胸', '肩', '三头'],
        sourceUrl: dayOneSourceUrl,
        exerciseIds: [
          'barbell-bench-press',
          'incline-dumbbell-press',
          'parallel-bar-dip',
          'skull-crusher',
          'y-raise',
        ],
        coachNotes: [
          {
            exerciseId: 'barbell-bench-press',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '作为胸肩三头日的主力复合推举，先建立稳定卧推动作和胸部张力。',
            keyCues: ['肩胛后收下沉，胸廓保持展开', '杠铃下放到胸部附近，不追求弹胸', '推起时手腕中立，肘部在可控路径内'],
            commonMistakes: ['臀部离凳造成代偿', '下放速度过快导致肩前侧不适', '手腕后折让力量漏掉'],
            illustration: 'bench',
            imageUrl: '/coach-shots/bench.jpg',
          },
          {
            exerciseId: 'incline-dumbbell-press',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '补上上胸推举角度，让胸上部在稳定轨迹里发力。',
            keyCues: ['凳面保持中等上斜，避免变成肩推', '哑铃下放时肘部略低于肩', '顶端不猛烈碰撞，保持胸部持续受力'],
            commonMistakes: ['凳子调得太陡', '下放过浅只做半程', '耸肩把压力转到斜方肌'],
            illustration: 'bench',
            imageUrl: '/coach-shots/incline.jpg',
          },
          {
            exerciseId: 'parallel-bar-dip',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用自重推举衔接胸和三头，能力不足时先做退阶版本。',
            keyCues: ['身体略前倾，肩胛保持稳定', '下放到肩部舒适的深度即可', '推起时胸和三头一起发力，不要只顶肩'],
            commonMistakes: ['下放过深引发肩前侧压力', '摆动借力', '肘部完全外翻'],
            regression: '做不了完整双杠时，用辅助器械、弹力带或脚支撑退阶。',
            illustration: 'dip',
            imageUrl: '/coach-shots/dip.jpg',
          },
          {
            exerciseId: 'skull-crusher',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '把三头从复合推举里单独拉出来，重点练伸肘控制。',
            keyCues: ['大臂略向后倾并尽量固定', '下放到额头后侧附近，保持可控', '伸肘时想象把杠推回起点'],
            commonMistakes: ['肘部明显外开', '肩关节大幅前后摆', '重量过大导致动作砸落'],
            illustration: 'bench',
            imageUrl: '/coach-shots/triceps.jpg',
          },
          {
            exerciseId: 'y-raise',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用轻重量补肩部外展和上举角度，作为胸肩三头日的收尾刺激。',
            keyCues: ['手臂沿斜前方抬成 Y 字轨迹', '用小重量保持肩部控制', '顶端短暂停顿，避免耸肩'],
            commonMistakes: ['甩动身体借力', '抬成普通前平举', '肩膀耸起抢发力'],
            illustration: 'raise',
            imageUrl: '/coach-shots/raise.jpg',
          },
        ],
      },
      {
        id: 'day-2-pull',
        name: 'Day 2 背 / 后束 / 二头',
        focus: ['背', '肩', '二头'],
        sourceUrl: dayTwoSourceUrl,
        exerciseIds: [
          'pull-up',
          'lat-pulldown',
          'barbell-row',
          'seated-cable-row',
          'rear-delt-fly',
          'barbell-curl',
        ],
        coachNotes: [
          {
            exerciseId: 'pull-up',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '先用垂直拉建立背部发力，能做标准动作再追求次数。',
            keyCues: ['先下沉肩胛再屈肘拉起', '胸口主动靠近杠', '下放时保持控制，不要直接掉下去'],
            commonMistakes: ['摆动借力', '只用二头硬拉', '下放不完整'],
            illustration: 'pull',
            imageUrl: '/coach-shots/pull.jpg',
          },
          {
            exerciseId: 'lat-pulldown',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '在更可控的器械里补足背阔肌垂直拉容量。',
            keyCues: ['胸口上挺，肋骨不要乱翻', '肘部向下向后走', '拉到锁骨附近后控制还原'],
            commonMistakes: ['身体后仰过多', '耸肩拉重量', '手腕过度发力'],
            illustration: 'pull',
            imageUrl: '/coach-shots/lat-pulldown.jpg',
          },
          {
            exerciseId: 'barbell-row',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用水平划船增加中背厚度和整体背部张力。',
            keyCues: ['髋部折叠，背部保持中立', '杠铃贴近腿部路径上拉', '肘部向后收，不要只抬手'],
            commonMistakes: ['腰背弯曲', '上半身起伏太大', '拉到胸前过高'],
            illustration: 'row',
            imageUrl: '/coach-shots/row.jpg',
          },
          {
            exerciseId: 'seated-cable-row',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用稳定坐姿继续累积划船容量，减少腰背代偿。',
            keyCues: ['躯干保持稳定', '肩胛向后收再让肘走', '手柄拉向腹部附近'],
            commonMistakes: ['身体前后晃动借力', '耸肩', '只用手臂拉'],
            illustration: 'row',
            imageUrl: '/coach-shots/seated-cable-row.jpg',
          },
          {
            exerciseId: 'rear-delt-fly',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '把后束单独补出来，让拉日不只练背阔和二头。',
            keyCues: ['髋部折叠，躯干稳定', '肘部微屈并向外展开', '用后束带动，不追求大重量'],
            commonMistakes: ['斜方肌代偿', '手臂伸太直', '甩动哑铃'],
            illustration: 'raise',
            imageUrl: '/coach-shots/rear-delt-fly.jpg',
          },
          {
            exerciseId: 'barbell-curl',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '在背部训练后直接补二头屈肘力量。',
            keyCues: ['大臂贴近身体', '顶端收缩但不把肘甩到前面', '离心下放保持慢和稳'],
            commonMistakes: ['身体后仰借力', '下放不完整', '手腕乱折'],
            illustration: 'curl',
            imageUrl: '/coach-shots/curl.jpg',
          },
        ],
      },
      {
        id: 'day-3-legs',
        name: 'Day 3 腿部',
        focus: ['腿', '臀'],
        sourceUrl: dayThreeSourceUrl,
        exerciseIds: [
          'squat',
          'leg-press',
          'romanian-deadlift',
          'leg-extension',
          'leg-curl',
          'standing-calf-raise',
        ],
        coachNotes: [
          {
            exerciseId: 'squat',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用深蹲作为腿日主力动作，统一练股四头、臀和核心支撑。',
            keyCues: ['脚掌踩稳，重心压在中足', '膝盖跟随脚尖方向', '下蹲和起身都保持躯干张力'],
            commonMistakes: ['膝盖内扣', '塌腰', '起身时臀部先抬'],
            illustration: 'squat',
            imageUrl: '/coach-shots/squat.jpg',
          },
          {
            exerciseId: 'leg-press',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '在器械里继续堆腿部容量，降低平衡限制。',
            keyCues: ['腰背贴住靠垫', '膝盖沿脚尖方向弯曲', '下放到骨盆仍稳定的深度'],
            commonMistakes: ['臀部卷离靠垫', '膝盖内扣', '顶端锁死膝盖休息'],
            illustration: 'leg-machine',
            imageUrl: '/coach-shots/leg-machine.jpg',
          },
          {
            exerciseId: 'romanian-deadlift',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '把腘绳肌和臀后侧单独拉出来训练。',
            keyCues: ['髋部向后推，不是主动蹲下', '杠铃贴近腿部下放', '感到腘绳肌拉伸后再髋伸站起'],
            commonMistakes: ['膝盖弯曲过多变深蹲', '腰背弯曲', '杠铃离身体太远'],
            illustration: 'hinge',
            imageUrl: '/coach-shots/hinge.jpg',
          },
          {
            exerciseId: 'leg-extension',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用孤立动作补股四头肌收缩感。',
            keyCues: ['膝关节对准器械轴心', '顶端收缩股四头肌', '下放时别让重量砸回去'],
            commonMistakes: ['重量过大甩动', '坐姿滑动', '顶端不控制'],
            illustration: 'leg-machine',
            imageUrl: '/coach-shots/leg-extension.jpg',
          },
          {
            exerciseId: 'leg-curl',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '补腘绳肌屈膝能力，和罗马尼亚硬拉形成互补。',
            keyCues: ['髋部贴稳垫子', '脚跟向臀部方向卷', '离心下放保持慢'],
            commonMistakes: ['臀部抬起借力', '动作幅度太短', '用惯性甩重量'],
            illustration: 'leg-machine',
            imageUrl: '/coach-shots/leg-curl.jpg',
          },
          {
            exerciseId: 'standing-calf-raise',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '在腿日末尾补小腿完整收缩和拉伸。',
            keyCues: ['脚跟充分下放', '顶端踮高后短暂停顿', '全程控制脚踝方向'],
            commonMistakes: ['弹震借力', '幅度太短', '脚踝内外翻'],
            illustration: 'calf',
            imageUrl: '/coach-shots/calf.jpg',
          },
        ],
      },
    ],
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return exercises.find((exercise) => exercise.id === id);
}

export function searchExercises(query: string): Exercise[] {
  const normalizedQuery = query.trim().toLowerCase();

  if (!normalizedQuery) {
    return exercises;
  }

  return exercises.filter((exercise) => {
    const searchable = [
      exercise.name,
      exercise.equipment,
      ...exercise.muscleGroups,
      ...exercise.cues,
      ...exercise.commonMistakes,
    ]
      .join(' ')
      .toLowerCase();

    return searchable.includes(normalizedQuery);
  });
}

export type ExerciseFilter = '全部' | MuscleGroup | '手臂';

export function filterExercises(query: string, filter: ExerciseFilter): Exercise[] {
  const results = searchExercises(query);

  if (filter === '全部') {
    return results;
  }

  if (filter === '手臂') {
    return results.filter(
      (exercise) => exercise.muscleGroups.includes('二头') || exercise.muscleGroups.includes('三头'),
    );
  }

  return results.filter((exercise) => exercise.muscleGroups.includes(filter));
}
