import type { CoachPlan, Exercise, MuscleGroup } from './types';

const sourceUrl = 'https://www.bilibili.com/video/BV1FcdZBNEm3/';
const dayOneSourceUrl = 'https://www.bilibili.com/video/BV1CSoKBaEgK/';
const dayTwoSourceUrl = 'https://www.bilibili.com/video/BV1v5opBhEDc/';
const dayThreeSourceUrl = 'https://www.bilibili.com/video/BV17aovBqEdg/';
const privateCoachingBackUrl = 'https://www.bilibili.com/video/BV1HR7o6CE8q/';
const privateCoachingArmsUrl = 'https://www.bilibili.com/video/BV1GzEg6wEVb/';
const privateCoachingChestUrl = 'https://www.bilibili.com/video/BV1ZxEk6cEv1/';
const privateCoachingShouldersUrl = 'https://www.bilibili.com/video/BV1csj36CEf9/';

export const exercises: Exercise[] = [
  {
    id: 'barbell-bench-press',
    name: '杠铃卧推',
    muscleGroups: ['胸', '三头', '肩'],
    equipment: '杠铃',
    cues: ['肩胛后收下沉', '下放到胸部附近', '推起时保持手腕中立'],
    commonMistakes: ['臀部离凳', '手腕过度后折', '下放路径过高'],
    planFit: ['Day 1'],
  },
  {
    id: 'incline-dumbbell-press',
    name: '上斜哑铃卧推',
    muscleGroups: ['胸', '肩', '三头'],
    equipment: '哑铃',
    cues: ['凳面保持上斜', '肘部略低于肩', '顶端不猛烈碰撞哑铃'],
    commonMistakes: ['斜度过高变成肩推', '下放过浅', '耸肩发力'],
    planFit: ['Day 1'],
  },
  {
    id: 'dumbbell-fly',
    name: '哑铃飞鸟',
    muscleGroups: ['胸'],
    equipment: '哑铃',
    cues: ['肘部微屈固定', '胸肌拉伸后夹回', '动作节奏放慢'],
    commonMistakes: ['手臂完全伸直', '重量过大', '变成推举'],
    planFit: ['Day 1'],
  },
  {
    id: 'cable-crossover',
    name: '绳索夹胸',
    muscleGroups: ['胸'],
    equipment: '龙门架',
    cues: ['身体微前倾', '手臂弧线向内夹', '顶端收缩胸肌'],
    commonMistakes: ['借助身体摆动', '耸肩', '只用手臂拉'],
    planFit: ['Day 1'],
  },
  {
    id: 'push-up',
    name: '俯卧撑',
    muscleGroups: ['胸', '三头', '核心'],
    equipment: '自重',
    cues: ['身体成直线', '胸部主动靠近地面', '推起时核心收紧'],
    commonMistakes: ['塌腰', '半程动作', '肘部完全外展'],
    planFit: ['Day 1'],
  },
  {
    id: 'overhead-press',
    name: '杠铃推举',
    muscleGroups: ['肩', '三头'],
    equipment: '杠铃',
    cues: ['核心收紧', '杠铃贴近面部上行', '顶端稳定锁定'],
    commonMistakes: ['腰椎过度后仰', '杠铃路径太远', '借腿过多'],
    planFit: ['Day 1'],
  },
  {
    id: 'dumbbell-shoulder-press',
    name: '哑铃肩推',
    muscleGroups: ['肩', '三头'],
    equipment: '哑铃',
    cues: ['前臂接近垂直', '推起不过度撞击', '下放到可控深度'],
    commonMistakes: ['耸肩', '手腕不稳', '下放过快'],
    planFit: ['Day 1'],
  },
  {
    id: 'lateral-raise',
    name: '哑铃侧平举',
    muscleGroups: ['肩'],
    equipment: '哑铃',
    cues: ['肘部带动上抬', '停在肩高附近', '保持躯干稳定'],
    commonMistakes: ['甩动借力', '耸肩', '手腕高于肘部过多'],
    planFit: ['Day 1'],
  },
  {
    id: 'cable-lateral-raise',
    name: '绳索侧平举',
    muscleGroups: ['肩'],
    equipment: '龙门架',
    cues: ['站位让阻力持续', '小臂放松', '顶端短暂停顿'],
    commonMistakes: ['身体大幅摆动', '重量过大', '斜方肌代偿'],
    planFit: ['Day 1'],
  },
  {
    id: 'triceps-pushdown',
    name: '绳索下压',
    muscleGroups: ['三头'],
    equipment: '绳索',
    cues: ['夹紧大臂', '肘关节固定', '底端充分伸肘'],
    commonMistakes: ['肩膀参与下压', '身体前后晃', '半程动作'],
    planFit: ['Day 1'],
  },
  {
    id: 'skull-crusher',
    name: '仰卧臂屈伸',
    muscleGroups: ['三头'],
    equipment: '杠铃',
    cues: ['大臂略向后倾', '控制下放到额头后侧', '伸肘发力'],
    commonMistakes: ['肘部外开', '下放砸向额头', '肩关节移动过多'],
    planFit: ['Day 1'],
  },
  {
    id: 'parallel-bar-dip',
    name: '双杠臂屈伸',
    muscleGroups: ['胸', '三头', '肩'],
    equipment: '双杠',
    cues: ['身体略前倾', '肩胛保持稳定', '推起时用胸和三头协同发力'],
    commonMistakes: ['下放失控', '肩膀顶到耳朵', '肘部完全外翻'],
    planFit: ['Day 1'],
  },
  {
    id: 'y-raise',
    name: 'Y 字侧平举',
    muscleGroups: ['肩'],
    equipment: '哑铃',
    cues: ['手臂沿斜前方抬起', '小重量控制轨迹', '顶端感受肩部发力'],
    commonMistakes: ['重量过大甩动', '耸肩代偿', '抬成正前平举'],
    planFit: ['Day 1'],
  },
  {
    id: 'close-grip-bench',
    name: '窄握卧推',
    muscleGroups: ['三头', '胸'],
    equipment: '杠铃',
    cues: ['握距略窄于卧推', '肘部贴近身体', '稳定下放'],
    commonMistakes: ['握距过窄压手腕', '肘部乱晃', '借胸过多'],
    planFit: ['Day 1'],
  },
  {
    id: 'pull-up',
    name: '引体向上',
    muscleGroups: ['背', '二头'],
    equipment: '单杠',
    cues: ['先下沉肩胛', '胸部靠近杠', '控制下放'],
    commonMistakes: ['只用手臂拉', '摆动借力', '下放不完整'],
    planFit: ['Day 2'],
  },
  {
    id: 'lat-pulldown',
    name: '高位下拉',
    muscleGroups: ['背', '二头'],
    equipment: '器械',
    cues: ['胸口上挺', '肘部向下向后', '拉到锁骨附近'],
    commonMistakes: ['身体后仰过多', '耸肩', '用手腕硬拉'],
    planFit: ['Day 2'],
  },
  {
    id: 'barbell-row',
    name: '杠铃划船',
    muscleGroups: ['背', '二头'],
    equipment: '杠铃',
    cues: ['髋部折叠', '背部保持中立', '肘部向后拉'],
    commonMistakes: ['腰背弯曲', '身体起伏太大', '拉到胸前过高'],
    planFit: ['Day 2'],
  },
  {
    id: 'seated-cable-row',
    name: '坐姿绳索划船',
    muscleGroups: ['背', '二头'],
    equipment: '绳索',
    cues: ['躯干稳定', '肩胛后收', '手柄拉向腹部'],
    commonMistakes: ['前后大幅晃动', '耸肩', '手臂先疲劳'],
    planFit: ['Day 2'],
  },
  {
    id: 'one-arm-dumbbell-row',
    name: '单臂哑铃划船',
    muscleGroups: ['背'],
    equipment: '哑铃',
    cues: ['支撑侧稳定', '肘部贴身体向后', '顶端挤压背部'],
    commonMistakes: ['转体过大', '耸肩', '只做半程'],
    planFit: ['Day 2'],
  },
  {
    id: 'straight-arm-pulldown',
    name: '直臂下压',
    muscleGroups: ['背'],
    equipment: '绳索',
    cues: ['手臂微屈固定', '肩关节带动下压', '感受背阔肌收缩'],
    commonMistakes: ['变成三头下压', '耸肩', '身体摇摆'],
    planFit: ['Day 2'],
  },
  {
    id: 'face-pull',
    name: '面拉',
    muscleGroups: ['肩', '背'],
    equipment: '绳索',
    cues: ['拉向面部', '肘部打开', '顶端外旋'],
    commonMistakes: ['重量过大', '下背代偿', '拉得太低'],
    planFit: ['Day 2'],
  },
  {
    id: 'rear-delt-fly',
    name: '俯身反向飞鸟',
    muscleGroups: ['肩', '背'],
    equipment: '哑铃',
    cues: ['髋部折叠', '肘部微屈', '后束带动外展'],
    commonMistakes: ['斜方肌代偿', '甩动借力', '手臂过度伸直'],
    planFit: ['Day 2'],
  },
  {
    id: 'barbell-curl',
    name: '杠铃弯举',
    muscleGroups: ['二头'],
    equipment: '杠铃',
    cues: ['大臂贴近身体', '控制离心下放', '顶端收缩二头'],
    commonMistakes: ['身体后仰借力', '肘部前移过多', '下放不完全'],
    planFit: ['Day 2'],
  },
  {
    id: 'dumbbell-curl',
    name: '哑铃弯举',
    muscleGroups: ['二头'],
    equipment: '哑铃',
    cues: ['掌心逐渐向上', '两侧节奏一致', '保持肩部放松'],
    commonMistakes: ['甩动', '耸肩', '只做上半程'],
    planFit: ['Day 2'],
  },
  {
    id: 'hammer-curl',
    name: '锤式弯举',
    muscleGroups: ['二头'],
    equipment: '哑铃',
    cues: ['掌心相对', '手腕中立', '控制重量下放'],
    commonMistakes: ['肘部乱晃', '耸肩', '速度过快'],
    planFit: ['Day 2'],
  },
  {
    id: 'squat',
    name: '杠铃深蹲',
    muscleGroups: ['腿', '臀', '核心'],
    equipment: '杠铃',
    cues: ['脚掌稳固', '膝盖跟随脚尖', '躯干保持张力'],
    commonMistakes: ['膝盖内扣', '塌腰', '重心前移'],
    planFit: ['Day 3'],
  },
  {
    id: 'front-squat',
    name: '前蹲',
    muscleGroups: ['腿', '核心'],
    equipment: '杠铃',
    cues: ['肘部抬高', '躯干更直立', '下蹲保持核心收紧'],
    commonMistakes: ['肘部下掉', '上背松', '脚跟离地'],
    planFit: ['Day 3'],
  },
  {
    id: 'leg-press',
    name: '腿举',
    muscleGroups: ['腿', '臀'],
    equipment: '器械',
    cues: ['腰背贴住靠垫', '膝盖沿脚尖方向', '控制下放深度'],
    commonMistakes: ['臀部卷离靠垫', '膝盖内扣', '锁死膝盖'],
    planFit: ['Day 3'],
  },
  {
    id: 'romanian-deadlift',
    name: '罗马尼亚硬拉',
    muscleGroups: ['腿', '臀', '背'],
    equipment: '杠铃',
    cues: ['髋部向后推', '杠铃贴近腿', '感受腘绳肌拉伸'],
    commonMistakes: ['膝盖弯曲过多', '腰背弯曲', '杠铃远离身体'],
    planFit: ['Day 3'],
  },
  {
    id: 'deadlift',
    name: '传统硬拉',
    muscleGroups: ['全身', '背', '腿', '臀'],
    equipment: '杠铃',
    cues: ['杠铃贴近小腿', '背部保持中立', '腿和髋协同发力'],
    commonMistakes: ['起拉时弓背', '臀部先抬', '杠铃绕膝'],
    planFit: ['Day 3'],
  },
  {
    id: 'leg-extension',
    name: '腿屈伸',
    muscleGroups: ['腿'],
    equipment: '器械',
    cues: ['膝关节对准轴心', '顶端收缩股四头肌', '慢速下放'],
    commonMistakes: ['重量过大甩动', '坐姿不稳', '底部放松过久'],
    planFit: ['Day 3'],
  },
  {
    id: 'leg-curl',
    name: '腿弯举',
    muscleGroups: ['腿'],
    equipment: '器械',
    cues: ['髋部贴稳垫子', '脚跟向臀部卷', '控制离心'],
    commonMistakes: ['臀部抬起', '借惯性', '动作幅度太短'],
    planFit: ['Day 3'],
  },
  {
    id: 'walking-lunge',
    name: '行走弓步',
    muscleGroups: ['腿', '臀'],
    equipment: '哑铃',
    cues: ['步幅稳定', '前脚全脚掌发力', '躯干保持直立'],
    commonMistakes: ['膝盖内扣', '身体左右晃', '步幅忽大忽小'],
    planFit: ['Day 3'],
  },
  {
    id: 'bulgarian-split-squat',
    name: '保加利亚分腿蹲',
    muscleGroups: ['腿', '臀'],
    equipment: '哑铃',
    cues: ['前脚站稳', '后脚只辅助平衡', '下放到可控深度'],
    commonMistakes: ['身体前扑', '前膝内扣', '左右差异过大'],
    planFit: ['Day 3'],
  },
  {
    id: 'hip-thrust',
    name: '臀推',
    muscleGroups: ['臀', '腿'],
    equipment: '杠铃',
    cues: ['上背支撑稳定', '顶端骨盆后倾', '用臀部推起'],
    commonMistakes: ['腰部代偿', '脚距不合适', '顶端过度挺腰'],
    planFit: ['Day 3'],
  },
  {
    id: 'standing-calf-raise',
    name: '站姿提踵',
    muscleGroups: ['腿'],
    equipment: '器械',
    cues: ['脚跟充分下放', '顶端踮高停顿', '膝盖保持稳定'],
    commonMistakes: ['弹震借力', '幅度太短', '脚踝内外翻'],
    planFit: ['Day 3'],
  },
  {
    id: 'plank',
    name: '平板支撑',
    muscleGroups: ['核心'],
    equipment: '自重',
    cues: ['肋骨下沉', '臀腹同时收紧', '身体保持直线'],
    commonMistakes: ['塌腰', '臀部过高', '憋气'],
    planFit: ['辅助'],
  },
  {
    id: 'hanging-leg-raise',
    name: '悬垂举腿',
    muscleGroups: ['核心'],
    equipment: '单杠',
    cues: ['骨盆后倾卷起', '控制下放', '减少身体摆动'],
    commonMistakes: ['甩腿', '只抬髋不卷腹', '握力先耗尽'],
    planFit: ['辅助'],
  },
  {
    id: 'cable-crunch',
    name: '绳索卷腹',
    muscleGroups: ['核心'],
    equipment: '绳索',
    cues: ['脊柱逐节卷曲', '骨盆稳定', '腹部主动收缩'],
    commonMistakes: ['髋部折叠代偿', '手臂拉绳', '重量过大'],
    planFit: ['辅助'],
  },
  {
    id: 'farmer-carry',
    name: '农夫行走',
    muscleGroups: ['全身', '核心'],
    equipment: '哑铃',
    cues: ['身体站高', '肩胛稳定', '步伐均匀'],
    commonMistakes: ['身体歪斜', '耸肩', '走得过快失控'],
    planFit: ['辅助'],
  },
  {
    id: 'kettlebell-swing',
    name: '壶铃摆荡',
    muscleGroups: ['臀', '腿', '核心'],
    equipment: '壶铃',
    cues: ['髋部主导', '手臂像绳子', '顶端臀部收紧'],
    commonMistakes: ['蹲起代替髋伸', '用肩抬壶铃', '腰背松散'],
    planFit: ['辅助'],
  },
  {
    id: 'ab-wheel-rollout',
    name: '健腹轮',
    muscleGroups: ['核心'],
    equipment: '健腹轮',
    cues: ['骨盆后倾', '向前推出到可控距离', '用腹部把身体拉回'],
    commonMistakes: ['塌腰', '推出过远失控', '只用手臂拉回'],
    planFit: ['辅助'],
  },
];

export const coachPlans: CoachPlan[] = [
  {
    id: 'kaishengwang-tanchengyi-three-day-split',
    coachName: '凯圣王-谭成义',
    title: '三分化训练计划',
    description: '以胸肩三头、背后束二头、腿部三天为骨架的力量训练跟练计划。动作要点根据 B 站跟练视频音轨转写整理，并保留原视频入口。',
    sourceUrl,
    planType: 'builtin',
    days: [
      {
        id: 'day-1-push',
        name: 'Day 1 胸 / 肩 / 三头',
        focus: ['胸', '肩', '三头'],
        sourceUrl: dayOneSourceUrl,
        exerciseIds: [
          'barbell-bench-press',
          'incline-dumbbell-press',
          'parallel-bar-dip',
          'skull-crusher',
          'y-raise',
        ],
        coachNotes: [
          {
            exerciseId: 'barbell-bench-press',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '作为胸肩三头日的主力复合推举，先建立稳定卧推动作和胸部张力。',
            keyCues: ['肩胛后收下沉，胸廓保持展开', '杠铃下放到胸部附近，不追求弹胸', '推起时手腕中立，肘部在可控路径内'],
            commonMistakes: ['臀部离凳造成代偿', '下放速度过快导致肩前侧不适', '手腕后折让力量漏掉'],
            illustration: 'bench',
            imageUrl: '/coach-shots/bench-cue.jpg',
          },
          {
            exerciseId: 'incline-dumbbell-press',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '补上上胸推举角度，让胸上部在稳定轨迹里发力。',
            keyCues: ['凳面保持中等上斜，避免变成肩推', '哑铃下放时肘部略低于肩', '顶端不猛烈碰撞，保持胸部持续受力'],
            commonMistakes: ['凳子调得太陡', '下放过浅只做半程', '耸肩把压力转到斜方肌'],
            illustration: 'bench',
            imageUrl: '/coach-shots/incline-cue.jpg',
          },
          {
            exerciseId: 'parallel-bar-dip',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用自重推举衔接胸和三头，能力不足时先做退阶版本。',
            keyCues: ['身体略前倾，肩胛保持稳定', '下放到肩部舒适的深度即可', '推起时胸和三头一起发力，不要只顶肩'],
            commonMistakes: ['下放过深引发肩前侧压力', '摆动借力', '肘部完全外翻'],
            regression: '做不了完整双杠时，用辅助器械、弹力带或脚支撑退阶。',
            illustration: 'dip',
            imageUrl: '/coach-shots/dip-cue.jpg',
          },
          {
            exerciseId: 'skull-crusher',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '把三头从复合推举里单独拉出来，重点练伸肘控制。',
            keyCues: ['大臂略向后倾并尽量固定', '下放到额头后侧附近，保持可控', '伸肘时想象把杠推回起点'],
            commonMistakes: ['肘部明显外开', '肩关节大幅前后摆', '重量过大导致动作砸落'],
            illustration: 'bench',
            imageUrl: '/coach-shots/triceps-cue.jpg',
          },
          {
            exerciseId: 'y-raise',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用轻重量补肩部外展和上举角度，作为胸肩三头日的收尾刺激。',
            keyCues: ['手臂沿斜前方抬成 Y 字轨迹', '用小重量保持肩部控制', '顶端短暂停顿，避免耸肩'],
            commonMistakes: ['甩动身体借力', '抬成普通前平举', '肩膀耸起抢发力'],
            illustration: 'raise',
            imageUrl: '/coach-shots/raise-cue.jpg',
          },
        ],
      },
      {
        id: 'day-2-pull',
        name: 'Day 2 背 / 后束 / 二头',
        focus: ['背', '肩', '二头'],
        sourceUrl: dayTwoSourceUrl,
        exerciseIds: [
          'pull-up',
          'lat-pulldown',
          'barbell-row',
          'seated-cable-row',
          'rear-delt-fly',
          'barbell-curl',
        ],
        coachNotes: [
          {
            exerciseId: 'pull-up',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '先用垂直拉建立背部发力，能做标准动作再追求次数。',
            keyCues: ['先下沉肩胛再屈肘拉起', '胸口主动靠近杠', '下放时保持控制，不要直接掉下去'],
            commonMistakes: ['摆动借力', '只用二头硬拉', '下放不完整'],
            illustration: 'pull',
            imageUrl: '/coach-shots/pull-cue.jpg',
          },
          {
            exerciseId: 'lat-pulldown',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '在更可控的器械里补足背阔肌垂直拉容量。',
            keyCues: ['胸口上挺，肋骨不要乱翻', '肘部向下向后走', '拉到锁骨附近后控制还原'],
            commonMistakes: ['身体后仰过多', '耸肩拉重量', '手腕过度发力'],
            illustration: 'pull',
            imageUrl: '/coach-shots/lat-pulldown-cue.jpg',
          },
          {
            exerciseId: 'barbell-row',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用水平划船增加中背厚度和整体背部张力。',
            keyCues: ['髋部折叠，背部保持中立', '杠铃贴近腿部路径上拉', '肘部向后收，不要只抬手'],
            commonMistakes: ['腰背弯曲', '上半身起伏太大', '拉到胸前过高'],
            illustration: 'row',
            imageUrl: '/coach-shots/row-cue.jpg',
          },
          {
            exerciseId: 'seated-cable-row',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用稳定坐姿继续累积划船容量，减少腰背代偿。',
            keyCues: ['躯干保持稳定', '肩胛向后收再让肘走', '手柄拉向腹部附近'],
            commonMistakes: ['身体前后晃动借力', '耸肩', '只用手臂拉'],
            illustration: 'row',
            imageUrl: '/coach-shots/seated-cable-row-cue.jpg',
          },
          {
            exerciseId: 'rear-delt-fly',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '把后束单独补出来，让拉日不只练背阔和二头。',
            keyCues: ['髋部折叠，躯干稳定', '肘部微屈并向外展开', '用后束带动，不追求大重量'],
            commonMistakes: ['斜方肌代偿', '手臂伸太直', '甩动哑铃'],
            illustration: 'raise',
            imageUrl: '/coach-shots/rear-delt-fly-cue.jpg',
          },
          {
            exerciseId: 'barbell-curl',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '在背部训练后直接补二头屈肘力量。',
            keyCues: ['大臂贴近身体', '顶端收缩但不把肘甩到前面', '离心下放保持慢和稳'],
            commonMistakes: ['身体后仰借力', '下放不完整', '手腕乱折'],
            illustration: 'curl',
            imageUrl: '/coach-shots/curl-cue.jpg',
          },
        ],
      },
      {
        id: 'day-3-legs',
        name: 'Day 3 腿部',
        focus: ['腿', '臀'],
        sourceUrl: dayThreeSourceUrl,
        exerciseIds: [
          'squat',
          'leg-press',
          'romanian-deadlift',
          'leg-extension',
          'leg-curl',
          'standing-calf-raise',
        ],
        coachNotes: [
          {
            exerciseId: 'squat',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用深蹲作为腿日主力动作，统一练股四头、臀和核心支撑。',
            keyCues: ['脚掌踩稳，重心压在中足', '膝盖跟随脚尖方向', '下蹲和起身都保持躯干张力'],
            commonMistakes: ['膝盖内扣', '塌腰', '起身时臀部先抬'],
            illustration: 'squat',
            imageUrl: '/coach-shots/squat-cue.jpg',
          },
          {
            exerciseId: 'leg-press',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '在器械里继续堆腿部容量，降低平衡限制。',
            keyCues: ['腰背贴住靠垫', '膝盖沿脚尖方向弯曲', '下放到骨盆仍稳定的深度'],
            commonMistakes: ['臀部卷离靠垫', '膝盖内扣', '顶端锁死膝盖休息'],
            illustration: 'leg-machine',
            imageUrl: '/coach-shots/leg-machine-cue.jpg',
          },
          {
            exerciseId: 'romanian-deadlift',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '把腘绳肌和臀后侧单独拉出来训练。',
            keyCues: ['髋部向后推，不是主动蹲下', '杠铃贴近腿部下放', '感到腘绳肌拉伸后再髋伸站起'],
            commonMistakes: ['膝盖弯曲过多变深蹲', '腰背弯曲', '杠铃离身体太远'],
            illustration: 'hinge',
            imageUrl: '/coach-shots/hinge-cue.jpg',
          },
          {
            exerciseId: 'leg-extension',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用孤立动作补股四头肌收缩感。',
            keyCues: ['膝关节对准器械轴心', '顶端收缩股四头肌', '下放时别让重量砸回去'],
            commonMistakes: ['重量过大甩动', '坐姿滑动', '顶端不控制'],
            illustration: 'leg-machine',
            imageUrl: '/coach-shots/leg-extension-cue.jpg',
          },
          {
            exerciseId: 'leg-curl',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '补腘绳肌屈膝能力，和罗马尼亚硬拉形成互补。',
            keyCues: ['髋部贴稳垫子', '脚跟向臀部方向卷', '离心下放保持慢'],
            commonMistakes: ['臀部抬起借力', '动作幅度太短', '用惯性甩重量'],
            illustration: 'leg-machine',
            imageUrl: '/coach-shots/leg-curl-cue.jpg',
          },
          {
            exerciseId: 'standing-calf-raise',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '在腿日末尾补小腿完整收缩和拉伸。',
            keyCues: ['脚跟充分下放', '顶端踮高后短暂停顿', '全程控制脚踝方向'],
            commonMistakes: ['弹震借力', '幅度太短', '脚踝内外翻'],
            illustration: 'calf',
            imageUrl: '/coach-shots/calf-cue.jpg',
          },
        ],
      },
    ],
  },
  {
    id: 'tanchengyi-private-coaching-follow-along',
    coachName: '谭成义',
    title: '谭成义私教跟练',
    description:
      '按谭成义 B 站私教系列公开课整理的四天跟练计划，覆盖背部、手臂、胸部和肩部。视频未提供公开字幕，动作顺序与要点根据公开视频标题、标签、时长、主题和现有动作库保守整理。',
    sourceUrl: privateCoachingBackUrl,
    planType: 'builtin',
    days: [
      {
        id: 'private-day-1-back',
        name: 'Day 1 背部',
        focus: ['背', '二头'],
        sourceUrl: privateCoachingBackUrl,
        exerciseIds: [
          'lat-pulldown',
          'seated-cable-row',
          'barbell-row',
          'straight-arm-pulldown',
          'rear-delt-fly',
          'barbell-curl',
        ],
        coachNotes: [
          {
            exerciseId: 'lat-pulldown',
            sourceTitle: '谭成义私教系列——保姆级私教视角之背部训练',
            sourceUrl: privateCoachingBackUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '先用可控的垂直拉找到背阔肌发力，让背部训练不被手臂抢走。',
            keyCues: ['胸口上挺，先让肩胛下沉', '肘部向身体两侧下拉', '还原时保持背部张力，不要耸肩放松'],
            commonMistakes: ['身体后仰变成借力', '手腕主动拉重量', '只追求下拉高度忽略背部收缩'],
            illustration: 'pull',
            imageUrl: '/coach-shots/lat-pulldown-cue.jpg',
          },
          {
            exerciseId: 'seated-cable-row',
            sourceTitle: '谭成义私教系列——保姆级私教视角之背部训练',
            sourceUrl: privateCoachingBackUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用坐姿划船补中背厚度，同时保持身体稳定，减少腰背代偿。',
            keyCues: ['先稳住躯干，再让肩胛向后收', '手柄拉向腹部附近', '离心阶段慢慢送回，不要被重量拽走'],
            commonMistakes: ['身体前后大幅晃动', '耸肩夹脖子', '只用二头把手柄拉回来'],
            illustration: 'row',
            imageUrl: '/coach-shots/seated-cable-row-cue.jpg',
          },
          {
            exerciseId: 'barbell-row',
            sourceTitle: '谭成义私教系列——保姆级私教视角之背部训练',
            sourceUrl: privateCoachingBackUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '把背部训练从器械过渡到自由重量，强化髋部支撑和背部整体张力。',
            keyCues: ['髋部折叠，背部保持中立', '杠铃贴近身体路径上拉', '肘部向后走，顶端挤压中背'],
            commonMistakes: ['腰背弯曲', '上半身跟着重量起伏', '拉到胸前过高导致肩部代偿'],
            illustration: 'row',
            imageUrl: '/coach-shots/row-cue.jpg',
          },
          {
            exerciseId: 'straight-arm-pulldown',
            sourceTitle: '谭成义私教系列——保姆级私教视角之背部训练',
            sourceUrl: privateCoachingBackUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用直臂动作让背阔肌在不依赖二头的情况下继续收缩。',
            keyCues: ['手臂微屈并保持角度', '肩关节带动手臂向下压', '底端停一下，感受背阔肌收紧'],
            commonMistakes: ['做成三头下压', '身体前后摇摆', '重量过大导致动作变形'],
            illustration: 'pull',
            imageUrl: '/coach-shots/straight-arm-pulldown-cue.jpg',
          },
          {
            exerciseId: 'rear-delt-fly',
            sourceTitle: '谭成义私教系列——保姆级私教视角之背部训练',
            sourceUrl: privateCoachingBackUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '在背部课末尾补后束和上背控制，让肩背线条更完整。',
            keyCues: ['髋部折叠，手臂微屈', '后束带动手臂向外打开', '顶端短暂停顿，不追重量'],
            commonMistakes: ['斜方肌耸起抢发力', '甩动哑铃', '手臂完全伸直导致肩部不适'],
            illustration: 'raise',
            imageUrl: '/coach-shots/rear-delt-fly-cue.jpg',
          },
          {
            exerciseId: 'barbell-curl',
            sourceTitle: '谭成义私教系列——保姆级私教视角之背部训练',
            sourceUrl: privateCoachingBackUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '背部训练后用弯举补充二头屈肘能力。',
            keyCues: ['大臂贴近身体两侧', '顶端收缩但不把肘甩到前方', '下放阶段保持慢和稳'],
            commonMistakes: ['身体后仰借力', '下放不到位', '手腕乱折导致前臂先累'],
            illustration: 'curl',
            imageUrl: '/coach-shots/curl-cue.jpg',
          },
        ],
      },
      {
        id: 'private-day-2-arms',
        name: 'Day 2 手臂',
        focus: ['二头', '三头'],
        sourceUrl: privateCoachingArmsUrl,
        exerciseIds: [
          'barbell-curl',
          'dumbbell-curl',
          'hammer-curl',
          'triceps-pushdown',
          'skull-crusher',
          'close-grip-bench',
        ],
        coachNotes: [
          {
            exerciseId: 'barbell-curl',
            sourceTitle: '谭成义私教系列——第二期手臂教学',
            sourceUrl: privateCoachingArmsUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用杠铃弯举作为二头主力动作，建立稳定屈肘路径。',
            keyCues: ['大臂尽量固定在身体两侧', '顶端主动挤压二头', '离心下放慢，不要直接掉到底'],
            commonMistakes: ['后仰甩重量', '肘部明显前移', '只做上半程'],
            illustration: 'curl',
            imageUrl: '/coach-shots/curl-cue.jpg',
          },
          {
            exerciseId: 'dumbbell-curl',
            sourceTitle: '谭成义私教系列——第二期手臂教学',
            sourceUrl: privateCoachingArmsUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用哑铃补左右两侧控制，避免强侧一直代偿。',
            keyCues: ['两侧节奏一致', '弯举时掌心逐渐向上', '顶端停顿后再控制下放'],
            commonMistakes: ['左右重量路径不一致', '耸肩', '借身体摆动完成动作'],
            illustration: 'curl',
            imageUrl: '/coach-shots/dumbbell-curl-cue.jpg',
          },
          {
            exerciseId: 'hammer-curl',
            sourceTitle: '谭成义私教系列——第二期手臂教学',
            sourceUrl: privateCoachingArmsUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '补肱肌和前臂参与，让手臂训练不只停留在普通弯举。',
            keyCues: ['掌心相对，手腕保持中立', '肘部位置稳定', '下放到底前仍保持控制'],
            commonMistakes: ['手腕弯折', '肘部乱晃', '用惯性甩起来'],
            illustration: 'curl',
            imageUrl: '/coach-shots/hammer-curl-cue.jpg',
          },
          {
            exerciseId: 'triceps-pushdown',
            sourceTitle: '谭成义私教系列——第二期手臂教学',
            sourceUrl: privateCoachingArmsUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用绳索下压先找到三头伸肘收缩感。',
            keyCues: ['大臂夹紧身体，不跟着绳索上下跑', '底端充分伸肘', '还原时控制到三头仍有张力'],
            commonMistakes: ['用肩膀往下压', '身体前后晃动', '底端没有伸直'],
            illustration: 'bench',
            imageUrl: '/coach-shots/triceps-pushdown-cue.jpg',
          },
          {
            exerciseId: 'skull-crusher',
            sourceTitle: '谭成义私教系列——第二期手臂教学',
            sourceUrl: privateCoachingArmsUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用仰卧臂屈伸强化三头长头在拉伸位的控制。',
            keyCues: ['大臂略向后倾并保持稳定', '下放到额头后侧附近', '伸肘时不要让肩关节大幅摆动'],
            commonMistakes: ['肘部外开', '重量过大砸落', '肩关节代偿过多'],
            illustration: 'bench',
            imageUrl: '/coach-shots/triceps-cue.jpg',
          },
          {
            exerciseId: 'close-grip-bench',
            sourceTitle: '谭成义私教系列——第二期手臂教学',
            sourceUrl: privateCoachingArmsUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用窄握卧推把三头力量放回复合推举里。',
            keyCues: ['握距略窄于常规卧推', '肘部贴近身体路径下放', '推起时保持手腕中立'],
            commonMistakes: ['握距过窄压手腕', '肘部乱晃', '胸部代偿过多'],
            illustration: 'bench',
            imageUrl: '/coach-shots/close-grip-bench-cue.jpg',
          },
        ],
      },
      {
        id: 'private-day-3-chest',
        name: 'Day 3 胸部',
        focus: ['胸', '三头'],
        sourceUrl: privateCoachingChestUrl,
        exerciseIds: [
          'barbell-bench-press',
          'incline-dumbbell-press',
          'parallel-bar-dip',
          'dumbbell-fly',
          'cable-crossover',
        ],
        coachNotes: [
          {
            exerciseId: 'barbell-bench-press',
            sourceTitle: '谭成义私教系列——第三期胸部教学',
            sourceUrl: privateCoachingChestUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用卧推作为胸部课主力动作，先建立稳定肩胛和胸部张力。',
            keyCues: ['肩胛后收下沉，胸廓展开', '下放到胸部附近并保持控制', '推起时手腕中立，路径稳定'],
            commonMistakes: ['肩胛松掉', '下放过快弹胸', '手腕后折导致力量漏掉'],
            illustration: 'bench',
            imageUrl: '/coach-shots/bench-cue.jpg',
          },
          {
            exerciseId: 'incline-dumbbell-press',
            sourceTitle: '谭成义私教系列——第三期胸部教学',
            sourceUrl: privateCoachingChestUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '补上胸推举角度，让胸部刺激更完整。',
            keyCues: ['凳面中等上斜', '肘部略低于肩', '顶端不碰撞哑铃，保持胸部持续受力'],
            commonMistakes: ['斜度过高变肩推', '下放太浅', '耸肩抢发力'],
            illustration: 'bench',
            imageUrl: '/coach-shots/incline-cue.jpg',
          },
          {
            exerciseId: 'parallel-bar-dip',
            sourceTitle: '谭成义私教系列——第三期胸部教学',
            sourceUrl: privateCoachingChestUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用双杠臂屈伸补胸下部和三头协同推举。',
            keyCues: ['身体略前倾', '肩胛保持稳定', '推起时用胸和三头一起发力'],
            commonMistakes: ['下放过深压肩', '摆动借力', '肘部完全外翻'],
            regression: '做不了完整双杠时，用辅助器械、弹力带或脚支撑退阶。',
            illustration: 'dip',
            imageUrl: '/coach-shots/dip-cue.jpg',
          },
          {
            exerciseId: 'dumbbell-fly',
            sourceTitle: '谭成义私教系列——第三期胸部教学',
            sourceUrl: privateCoachingChestUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用飞鸟动作强调胸肌拉伸和夹回，不让胸部课只剩推举。',
            keyCues: ['肘部微屈并固定角度', '下放到胸部有拉伸即可', '夹回时想象让大臂靠近身体中线'],
            commonMistakes: ['手臂伸太直', '重量过大变推举', '底部下放过深压肩'],
            illustration: 'bench',
            imageUrl: '/coach-shots/dumbbell-fly-cue.jpg',
          },
          {
            exerciseId: 'cable-crossover',
            sourceTitle: '谭成义私教系列——第三期胸部教学',
            sourceUrl: privateCoachingChestUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用绳索夹胸在收尾阶段保留持续张力。',
            keyCues: ['身体微前倾', '手臂沿弧线向内夹', '顶端停顿并主动收缩胸肌'],
            commonMistakes: ['借身体摆动', '耸肩', '只用手臂硬拉绳索'],
            illustration: 'bench',
            imageUrl: '/coach-shots/cable-crossover-cue.jpg',
          },
        ],
      },
      {
        id: 'private-day-4-shoulders',
        name: 'Day 4 肩部',
        focus: ['肩'],
        sourceUrl: privateCoachingShouldersUrl,
        exerciseIds: [
          'dumbbell-shoulder-press',
          'lateral-raise',
          'cable-lateral-raise',
          'rear-delt-fly',
          'face-pull',
          'y-raise',
        ],
        coachNotes: [
          {
            exerciseId: 'dumbbell-shoulder-press',
            sourceTitle: '谭成义私教系列——肩部教学',
            sourceUrl: privateCoachingShouldersUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用肩推作为肩部课主力推举，建立稳定上举能力。',
            keyCues: ['核心收紧，肋骨不要外翻', '前臂接近垂直', '顶端稳定，不猛烈碰撞哑铃'],
            commonMistakes: ['腰椎后仰代偿', '耸肩', '下放过快失控'],
            illustration: 'raise',
            imageUrl: '/coach-shots/shoulder-press-cue.jpg',
          },
          {
            exerciseId: 'lateral-raise',
            sourceTitle: '谭成义私教系列——肩部教学',
            sourceUrl: privateCoachingShouldersUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用侧平举集中训练中束，强化肩宽视觉。',
            keyCues: ['肘部带动上抬', '抬到肩高附近即可', '用小重量控制轨迹'],
            commonMistakes: ['甩动借力', '耸肩', '手腕明显高于肘部'],
            illustration: 'raise',
            imageUrl: '/coach-shots/lateral-raise-cue.jpg',
          },
          {
            exerciseId: 'cable-lateral-raise',
            sourceTitle: '谭成义私教系列——肩部教学',
            sourceUrl: privateCoachingShouldersUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用绳索给侧平举补持续阻力，让中束在底部也有张力。',
            keyCues: ['站位让绳索始终有阻力', '小臂放松，肘部带动', '顶端短暂停顿'],
            commonMistakes: ['身体大幅摆动', '重量过大', '斜方肌代偿'],
            illustration: 'raise',
            imageUrl: '/coach-shots/cable-lateral-raise-cue.jpg',
          },
          {
            exerciseId: 'rear-delt-fly',
            sourceTitle: '谭成义私教系列——肩部教学',
            sourceUrl: privateCoachingShouldersUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '补后束训练，让肩部课不只练前束和中束。',
            keyCues: ['髋部折叠，躯干稳定', '肘部微屈向外打开', '顶端短暂停顿感受后束'],
            commonMistakes: ['斜方肌抢发力', '甩动哑铃', '只追求抬高不控制'],
            illustration: 'raise',
            imageUrl: '/coach-shots/rear-delt-fly-cue.jpg',
          },
          {
            exerciseId: 'face-pull',
            sourceTitle: '谭成义私教系列——肩部教学',
            sourceUrl: privateCoachingShouldersUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用面拉补肩胛控制和肩后侧稳定。',
            keyCues: ['绳索拉向面部高度', '肘部打开并做外旋', '顶端停一下再控制还原'],
            commonMistakes: ['重量过大拉成划船', '下背后仰代偿', '拉得太低'],
            illustration: 'pull',
            imageUrl: '/coach-shots/face-pull-cue.jpg',
          },
          {
            exerciseId: 'y-raise',
            sourceTitle: '谭成义私教系列——肩部教学',
            sourceUrl: privateCoachingShouldersUrl,
            sourceBasis: 'B站公开视频标题、标签与训练主题整理；字幕/AI总结未公开',
            goal: '用 Y 字轨迹收尾，补上肩部上举角度和控制感。',
            keyCues: ['手臂沿斜前方抬起', '全程小重量控制', '避免耸肩，用肩部带动'],
            commonMistakes: ['抬成普通前平举', '身体甩动', '肩膀顶到耳朵'],
            illustration: 'raise',
            imageUrl: '/coach-shots/raise-cue.jpg',
          },
        ],
      },
    ],
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return exercises.find((exercise) => exercise.id === id);
}

export function searchExercises(query: string): Exercise[] {
  const normalizedQuery = query.trim().toLowerCase();

  if (!normalizedQuery) {
    return exercises;
  }

  return exercises.filter((exercise) => {
    const searchable = [
      exercise.name,
      exercise.equipment,
      ...exercise.muscleGroups,
      ...exercise.cues,
      ...exercise.commonMistakes,
    ]
      .join(' ')
      .toLowerCase();

    return searchable.includes(normalizedQuery);
  });
}

export type ExerciseFilter = '全部' | MuscleGroup | '手臂';

export function filterExercises(query: string, filter: ExerciseFilter): Exercise[] {
  const results = searchExercises(query);

  if (filter === '全部') {
    return results;
  }

  if (filter === '手臂') {
    return results.filter(
      (exercise) => exercise.muscleGroups.includes('二头') || exercise.muscleGroups.includes('三头'),
    );
  }

  return results.filter((exercise) => exercise.muscleGroups.includes(filter));
}
