import type { CoachPlan, Exercise, MuscleGroup } from './types';

const sourceUrl = 'https://www.bilibili.com/video/BV1FcdZBNEm3/';
const dayOneSourceUrl = 'https://www.bilibili.com/video/BV1CSoKBaEgK/';
const dayTwoSourceUrl = 'https://www.bilibili.com/video/BV1v5opBhEDc/';
const dayThreeSourceUrl = 'https://www.bilibili.com/video/BV17aovBqEdg/';
const privateCoachingBackUrl = 'https://www.bilibili.com/video/BV1HR7o6CE8q/';
const privateCoachingArmsUrl = 'https://www.bilibili.com/video/BV1GzEg6wEVb/';
const privateCoachingChestUrl = 'https://www.bilibili.com/video/BV1ZxEk6cEv1/';
const privateCoachingShouldersUrl = 'https://www.bilibili.com/video/BV1csj36CEf9/';

export const exercises: Exercise[] = [
  {
    id: 'barbell-bench-press',
    name: '杠铃卧推',
    muscleGroups: ['胸', '三头', '肩'],
    equipment: '杠铃',
    cues: ['肩胛后收下沉', '下放到胸部附近', '推起时保持手腕中立'],
    commonMistakes: ['臀部离凳', '手腕过度后折', '下放路径过高'],
    planFit: ['Day 1'],
  },
  {
    id: 'incline-dumbbell-press',
    name: '上斜哑铃卧推',
    muscleGroups: ['胸', '肩', '三头'],
    equipment: '哑铃',
    cues: ['凳面保持上斜', '肘部略低于肩', '顶端不猛烈碰撞哑铃'],
    commonMistakes: ['斜度过高变成肩推', '下放过浅', '耸肩发力'],
    planFit: ['Day 1'],
  },
  {
    id: 'dumbbell-fly',
    name: '哑铃飞鸟',
    muscleGroups: ['胸'],
    equipment: '哑铃',
    cues: ['肘部微屈固定', '胸肌拉伸后夹回', '动作节奏放慢'],
    commonMistakes: ['手臂完全伸直', '重量过大', '变成推举'],
    planFit: ['Day 1'],
  },
  {
    id: 'cable-crossover',
    name: '绳索夹胸',
    muscleGroups: ['胸'],
    equipment: '龙门架',
    cues: ['身体微前倾', '手臂弧线向内夹', '顶端收缩胸肌'],
    commonMistakes: ['借助身体摆动', '耸肩', '只用手臂拉'],
    planFit: ['Day 1'],
  },
  {
    id: 'push-up',
    name: '俯卧撑',
    muscleGroups: ['胸', '三头', '核心'],
    equipment: '自重',
    cues: ['身体成直线', '胸部主动靠近地面', '推起时核心收紧'],
    commonMistakes: ['塌腰', '半程动作', '肘部完全外展'],
    planFit: ['Day 1'],
  },
  {
    id: 'overhead-press',
    name: '杠铃推举',
    muscleGroups: ['肩', '三头'],
    equipment: '杠铃',
    cues: ['核心收紧', '杠铃贴近面部上行', '顶端稳定锁定'],
    commonMistakes: ['腰椎过度后仰', '杠铃路径太远', '借腿过多'],
    planFit: ['Day 1'],
  },
  {
    id: 'dumbbell-shoulder-press',
    name: '哑铃肩推',
    muscleGroups: ['肩', '三头'],
    equipment: '哑铃',
    cues: ['前臂接近垂直', '推起不过度撞击', '下放到可控深度'],
    commonMistakes: ['耸肩', '手腕不稳', '下放过快'],
    planFit: ['Day 1'],
  },
  {
    id: 'lateral-raise',
    name: '哑铃侧平举',
    muscleGroups: ['肩'],
    equipment: '哑铃',
    cues: ['肘部带动上抬', '停在肩高附近', '保持躯干稳定'],
    commonMistakes: ['甩动借力', '耸肩', '手腕高于肘部过多'],
    planFit: ['Day 1'],
  },
  {
    id: 'cable-lateral-raise',
    name: '绳索侧平举',
    muscleGroups: ['肩'],
    equipment: '龙门架',
    cues: ['站位让阻力持续', '小臂放松', '顶端短暂停顿'],
    commonMistakes: ['身体大幅摆动', '重量过大', '斜方肌代偿'],
    planFit: ['Day 1'],
  },
  {
    id: 'triceps-pushdown',
    name: '绳索下压',
    muscleGroups: ['三头'],
    equipment: '绳索',
    cues: ['夹紧大臂', '肘关节固定', '底端充分伸肘'],
    commonMistakes: ['肩膀参与下压', '身体前后晃', '半程动作'],
    planFit: ['Day 1'],
  },
  {
    id: 'skull-crusher',
    name: '仰卧臂屈伸',
    muscleGroups: ['三头'],
    equipment: '杠铃',
    cues: ['大臂略向后倾', '控制下放到额头后侧', '伸肘发力'],
    commonMistakes: ['肘部外开', '下放砸向额头', '肩关节移动过多'],
    planFit: ['Day 1'],
  },
  {
    id: 'parallel-bar-dip',
    name: '双杠臂屈伸',
    muscleGroups: ['胸', '三头', '肩'],
    equipment: '双杠',
    cues: ['身体略前倾', '肩胛保持稳定', '推起时用胸和三头协同发力'],
    commonMistakes: ['下放失控', '肩膀顶到耳朵', '肘部完全外翻'],
    planFit: ['Day 1'],
  },
  {
    id: 'y-raise',
    name: 'Y 字侧平举',
    muscleGroups: ['肩'],
    equipment: '哑铃',
    cues: ['手臂沿斜前方抬起', '小重量控制轨迹', '顶端感受肩部发力'],
    commonMistakes: ['重量过大甩动', '耸肩代偿', '抬成正前平举'],
    planFit: ['Day 1'],
  },
  {
    id: 'close-grip-bench',
    name: '窄握卧推',
    muscleGroups: ['三头', '胸'],
    equipment: '杠铃',
    cues: ['握距略窄于卧推', '肘部贴近身体', '稳定下放'],
    commonMistakes: ['握距过窄压手腕', '肘部乱晃', '借胸过多'],
    planFit: ['Day 1'],
  },
  {
    id: 'pull-up',
    name: '引体向上',
    muscleGroups: ['背', '二头'],
    equipment: '单杠',
    cues: ['先下沉肩胛', '胸部靠近杠', '控制下放'],
    commonMistakes: ['只用手臂拉', '摆动借力', '下放不完整'],
    planFit: ['Day 2'],
  },
  {
    id: 'lat-pulldown',
    name: '高位下拉',
    muscleGroups: ['背', '二头'],
    equipment: '器械',
    cues: ['胸口上挺', '肘部向下向后', '拉到锁骨附近'],
    commonMistakes: ['身体后仰过多', '耸肩', '用手腕硬拉'],
    planFit: ['Day 2'],
  },
  {
    id: 'barbell-row',
    name: '杠铃划船',
    muscleGroups: ['背', '二头'],
    equipment: '杠铃',
    cues: ['髋部折叠', '背部保持中立', '肘部向后拉'],
    commonMistakes: ['腰背弯曲', '身体起伏太大', '拉到胸前过高'],
    planFit: ['Day 2'],
  },
  {
    id: 'seated-cable-row',
    name: '坐姿绳索划船',
    muscleGroups: ['背', '二头'],
    equipment: '绳索',
    cues: ['躯干稳定', '肩胛后收', '手柄拉向腹部'],
    commonMistakes: ['前后大幅晃动', '耸肩', '手臂先疲劳'],
    planFit: ['Day 2'],
  },
  {
    id: 'one-arm-dumbbell-row',
    name: '单臂哑铃划船',
    muscleGroups: ['背'],
    equipment: '哑铃',
    cues: ['支撑侧稳定', '肘部贴身体向后', '顶端挤压背部'],
    commonMistakes: ['转体过大', '耸肩', '只做半程'],
    planFit: ['Day 2'],
  },
  {
    id: 'straight-arm-pulldown',
    name: '直臂下压',
    muscleGroups: ['背'],
    equipment: '绳索',
    cues: ['手臂微屈固定', '肩关节带动下压', '感受背阔肌收缩'],
    commonMistakes: ['变成三头下压', '耸肩', '身体摇摆'],
    planFit: ['Day 2'],
  },
  {
    id: 'face-pull',
    name: '面拉',
    muscleGroups: ['肩', '背'],
    equipment: '绳索',
    cues: ['拉向面部', '肘部打开', '顶端外旋'],
    commonMistakes: ['重量过大', '下背代偿', '拉得太低'],
    planFit: ['Day 2'],
  },
  {
    id: 'rear-delt-fly',
    name: '俯身反向飞鸟',
    muscleGroups: ['肩', '背'],
    equipment: '哑铃',
    cues: ['髋部折叠', '肘部微屈', '后束带动外展'],
    commonMistakes: ['斜方肌代偿', '甩动借力', '手臂过度伸直'],
    planFit: ['Day 2'],
  },
  {
    id: 'barbell-curl',
    name: '杠铃弯举',
    muscleGroups: ['二头'],
    equipment: '杠铃',
    cues: ['大臂贴近身体', '控制离心下放', '顶端收缩二头'],
    commonMistakes: ['身体后仰借力', '肘部前移过多', '下放不完全'],
    planFit: ['Day 2'],
  },
  {
    id: 'dumbbell-curl',
    name: '哑铃弯举',
    muscleGroups: ['二头'],
    equipment: '哑铃',
    cues: ['掌心逐渐向上', '两侧节奏一致', '保持肩部放松'],
    commonMistakes: ['甩动', '耸肩', '只做上半程'],
    planFit: ['Day 2'],
  },
  {
    id: 'hammer-curl',
    name: '锤式弯举',
    muscleGroups: ['二头'],
    equipment: '哑铃',
    cues: ['掌心相对', '手腕中立', '控制重量下放'],
    commonMistakes: ['肘部乱晃', '耸肩', '速度过快'],
    planFit: ['Day 2'],
  },
  {
    id: 'squat',
    name: '杠铃深蹲',
    muscleGroups: ['腿', '臀', '核心'],
    equipment: '杠铃',
    cues: ['脚掌稳固', '膝盖跟随脚尖', '躯干保持张力'],
    commonMistakes: ['膝盖内扣', '塌腰', '重心前移'],
    planFit: ['Day 3'],
  },
  {
    id: 'front-squat',
    name: '前蹲',
    muscleGroups: ['腿', '核心'],
    equipment: '杠铃',
    cues: ['肘部抬高', '躯干更直立', '下蹲保持核心收紧'],
    commonMistakes: ['肘部下掉', '上背松', '脚跟离地'],
    planFit: ['Day 3'],
  },
  {
    id: 'leg-press',
    name: '腿举',
    muscleGroups: ['腿', '臀'],
    equipment: '器械',
    cues: ['腰背贴住靠垫', '膝盖沿脚尖方向', '控制下放深度'],
    commonMistakes: ['臀部卷离靠垫', '膝盖内扣', '锁死膝盖'],
    planFit: ['Day 3'],
  },
  {
    id: 'romanian-deadlift',
    name: '罗马尼亚硬拉',
    muscleGroups: ['腿', '臀', '背'],
    equipment: '杠铃',
    cues: ['髋部向后推', '杠铃贴近腿', '感受腘绳肌拉伸'],
    commonMistakes: ['膝盖弯曲过多', '腰背弯曲', '杠铃远离身体'],
    planFit: ['Day 3'],
  },
  {
    id: 'deadlift',
    name: '传统硬拉',
    muscleGroups: ['全身', '背', '腿', '臀'],
    equipment: '杠铃',
    cues: ['杠铃贴近小腿', '背部保持中立', '腿和髋协同发力'],
    commonMistakes: ['起拉时弓背', '臀部先抬', '杠铃绕膝'],
    planFit: ['Day 3'],
  },
  {
    id: 'leg-extension',
    name: '腿屈伸',
    muscleGroups: ['腿'],
    equipment: '器械',
    cues: ['膝关节对准轴心', '顶端收缩股四头肌', '慢速下放'],
    commonMistakes: ['重量过大甩动', '坐姿不稳', '底部放松过久'],
    planFit: ['Day 3'],
  },
  {
    id: 'leg-curl',
    name: '腿弯举',
    muscleGroups: ['腿'],
    equipment: '器械',
    cues: ['髋部贴稳垫子', '脚跟向臀部卷', '控制离心'],
    commonMistakes: ['臀部抬起', '借惯性', '动作幅度太短'],
    planFit: ['Day 3'],
  },
  {
    id: 'walking-lunge',
    name: '行走弓步',
    muscleGroups: ['腿', '臀'],
    equipment: '哑铃',
    cues: ['步幅稳定', '前脚全脚掌发力', '躯干保持直立'],
    commonMistakes: ['膝盖内扣', '身体左右晃', '步幅忽大忽小'],
    planFit: ['Day 3'],
  },
  {
    id: 'bulgarian-split-squat',
    name: '保加利亚分腿蹲',
    muscleGroups: ['腿', '臀'],
    equipment: '哑铃',
    cues: ['前脚站稳', '后脚只辅助平衡', '下放到可控深度'],
    commonMistakes: ['身体前扑', '前膝内扣', '左右差异过大'],
    planFit: ['Day 3'],
  },
  {
    id: 'hip-thrust',
    name: '臀推',
    muscleGroups: ['臀', '腿'],
    equipment: '杠铃',
    cues: ['上背支撑稳定', '顶端骨盆后倾', '用臀部推起'],
    commonMistakes: ['腰部代偿', '脚距不合适', '顶端过度挺腰'],
    planFit: ['Day 3'],
  },
  {
    id: 'standing-calf-raise',
    name: '站姿提踵',
    muscleGroups: ['腿'],
    equipment: '器械',
    cues: ['脚跟充分下放', '顶端踮高停顿', '膝盖保持稳定'],
    commonMistakes: ['弹震借力', '幅度太短', '脚踝内外翻'],
    planFit: ['Day 3'],
  },
  {
    id: 'plank',
    name: '平板支撑',
    muscleGroups: ['核心'],
    equipment: '自重',
    cues: ['肋骨下沉', '臀腹同时收紧', '身体保持直线'],
    commonMistakes: ['塌腰', '臀部过高', '憋气'],
    planFit: ['辅助'],
  },
  {
    id: 'hanging-leg-raise',
    name: '悬垂举腿',
    muscleGroups: ['核心'],
    equipment: '单杠',
    cues: ['骨盆后倾卷起', '控制下放', '减少身体摆动'],
    commonMistakes: ['甩腿', '只抬髋不卷腹', '握力先耗尽'],
    planFit: ['辅助'],
  },
  {
    id: 'cable-crunch',
    name: '绳索卷腹',
    muscleGroups: ['核心'],
    equipment: '绳索',
    cues: ['脊柱逐节卷曲', '骨盆稳定', '腹部主动收缩'],
    commonMistakes: ['髋部折叠代偿', '手臂拉绳', '重量过大'],
    planFit: ['辅助'],
  },
  {
    id: 'farmer-carry',
    name: '农夫行走',
    muscleGroups: ['全身', '核心'],
    equipment: '哑铃',
    cues: ['身体站高', '肩胛稳定', '步伐均匀'],
    commonMistakes: ['身体歪斜', '耸肩', '走得过快失控'],
    planFit: ['辅助'],
  },
  {
    id: 'kettlebell-swing',
    name: '壶铃摆荡',
    muscleGroups: ['臀', '腿', '核心'],
    equipment: '壶铃',
    cues: ['髋部主导', '手臂像绳子', '顶端臀部收紧'],
    commonMistakes: ['蹲起代替髋伸', '用肩抬壶铃', '腰背松散'],
    planFit: ['辅助'],
  },
  {
    id: 'ab-wheel-rollout',
    name: '健腹轮',
    muscleGroups: ['核心'],
    equipment: '健腹轮',
    cues: ['骨盆后倾', '向前推出到可控距离', '用腹部把身体拉回'],
    commonMistakes: ['塌腰', '推出过远失控', '只用手臂拉回'],
    planFit: ['辅助'],
  },
  {
    id: 'one-arm-cable-row',
    name: '单手绳索划船',
    muscleGroups: ['背', '二头'],
    equipment: '龙门架',
    cues: ['腿蹬住稳定骨盆', '另一只手撑住把身体推向远端', '微反手、向后做肩屈幅度'],
    commonMistakes: ['身体侧屈旋转代偿', '肘往上提', '还原时张力松掉'],
    planFit: ['Day 1'],
  },
  {
    id: 'one-arm-lat-pulldown',
    name: '单手全肩屈绳索下压',
    muscleGroups: ['背'],
    equipment: '龙门架',
    cues: ['手微外旋、手腕全程不动', '约20度后仰保持背预先发力', '向下拉而不是向后拉'],
    commonMistakes: ['过度侧屈或旋转', '向后缩变成手臂发力', '身体过度前倾'],
    planFit: ['Day 1'],
  },
  {
    id: 'chest-supported-row',
    name: '胸支撑肩胛后缩划船',
    muscleGroups: ['背'],
    equipment: '器械',
    cues: ['胸口贴住靠垫、躯干固定不动', '只做肩胛骨后缩、把幅度做到位', '不要顶腰代偿'],
    commonMistakes: ['用顶腰代替肩胛后缩', '躯干跟着晃动', '后缩幅度不足'],
    planFit: ['Day 1'],
  },
  {
    id: 'cable-curl',
    name: '坐姿绳索弯举',
    muscleGroups: ['二头'],
    equipment: '龙门架',
    cues: ['大臂压在膝上固定', '外旋位让二头内侧更饱满', '顶端完全收紧再控制下放'],
    commonMistakes: ['大臂离开支撑点', '只做半程', '靠惯性甩起'],
    planFit: ['Day 2'],
  },
  {
    id: 'incline-dumbbell-curl',
    name: '仰卧哑铃弯举',
    muscleGroups: ['二头'],
    equipment: '哑铃',
    cues: ['约45度斜板、肩屈位拉长二头', '保持外旋位充分拉伸', '下放时控制离心、别让肩前翻'],
    commonMistakes: ['凳子太低导致肩不适', '下放失控肩前翻', '没保持外旋'],
    planFit: ['Day 2'],
  },
  {
    id: 'chest-press-machine',
    name: '中下胸推举',
    muscleGroups: ['胸', '三头'],
    equipment: '器械',
    cues: ['半握靠尺侧、提升胸部收力', '腰贴住、配合开肋扩张前侧', '保持脊柱位置不变'],
    commonMistakes: ['全握增大肩关节压力', '顶腰换幅度', '胸部收缩不充分'],
    planFit: ['Day 3'],
  },
  {
    id: 'reverse-pec-deck',
    name: '坐姿反向飞鸟',
    muscleGroups: ['肩'],
    equipment: '器械',
    cues: ['座椅调高让手与肩同高', '重量、幅度、感受三者兼顾', '内旋位让后束更孤立'],
    commonMistakes: ['座椅过低变成上提', '耸肩抢发力', '重量过大失控'],
    planFit: ['Day 4'],
  },
  {
    id: 'front-raise',
    name: '哑铃前平举',
    muscleGroups: ['肩'],
    equipment: '哑铃',
    cues: ['对握从大腿前方起、保证前束持续发力', '抬到肩高、吸满气', '躯干不晃、不顶腰'],
    commonMistakes: ['起始位太低前束不发力', '身体摆动借力', '抬得过高耸肩'],
    planFit: ['Day 4'],
  },
];

export const coachPlans: CoachPlan[] = [
  {
    id: 'kaishengwang-tanchengyi-three-day-split',
    coachName: '凯圣王-谭成义',
    title: '三分化训练计划',
    description: '以胸肩三头、背后束二头、腿部三天为骨架的力量训练跟练计划。动作要点根据 B 站跟练视频音轨转写整理，并保留原视频入口。',
    sourceUrl,
    planType: 'builtin',
    days: [
      {
        id: 'day-1-push',
        name: 'Day 1 胸 / 肩 / 三头',
        focus: ['胸', '肩', '三头'],
        sourceUrl: dayOneSourceUrl,
        exerciseIds: [
          'barbell-bench-press',
          'incline-dumbbell-press',
          'parallel-bar-dip',
          'skull-crusher',
          'y-raise',
        ],
        coachNotes: [
          {
            exerciseId: 'barbell-bench-press',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '作为胸肩三头日的主力复合推举，先建立稳定卧推动作和胸部张力。',
            keyCues: ['肩胛后收下沉，胸廓保持展开', '杠铃下放到胸部附近，不追求弹胸', '推起时手腕中立，肘部在可控路径内'],
            commonMistakes: ['臀部离凳造成代偿', '下放速度过快导致肩前侧不适', '手腕后折让力量漏掉'],
            illustration: 'bench',
            imageUrl: '/coach-shots/bench-cue.jpg',
          },
          {
            exerciseId: 'incline-dumbbell-press',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '补上上胸推举角度，让胸上部在稳定轨迹里发力。',
            keyCues: ['凳面保持中等上斜，避免变成肩推', '哑铃下放时肘部略低于肩', '顶端不猛烈碰撞，保持胸部持续受力'],
            commonMistakes: ['凳子调得太陡', '下放过浅只做半程', '耸肩把压力转到斜方肌'],
            illustration: 'bench',
            imageUrl: '/coach-shots/incline-cue.jpg',
          },
          {
            exerciseId: 'parallel-bar-dip',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用自重推举衔接胸和三头，能力不足时先做退阶版本。',
            keyCues: ['身体略前倾，肩胛保持稳定', '下放到肩部舒适的深度即可', '推起时胸和三头一起发力，不要只顶肩'],
            commonMistakes: ['下放过深引发肩前侧压力', '摆动借力', '肘部完全外翻'],
            regression: '做不了完整双杠时，用辅助器械、弹力带或脚支撑退阶。',
            illustration: 'dip',
            imageUrl: '/coach-shots/dip-cue.jpg',
          },
          {
            exerciseId: 'skull-crusher',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '把三头从复合推举里单独拉出来，重点练伸肘控制。',
            keyCues: ['大臂略向后倾并尽量固定', '下放到额头后侧附近，保持可控', '伸肘时想象把杠推回起点'],
            commonMistakes: ['肘部明显外开', '肩关节大幅前后摆', '重量过大导致动作砸落'],
            illustration: 'bench',
            imageUrl: '/coach-shots/triceps-cue.jpg',
          },
          {
            exerciseId: 'y-raise',
            sourceTitle: '凯圣王-谭成义三分化②——跟练胸肩三头',
            sourceUrl: dayOneSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用轻重量补肩部外展和上举角度，作为胸肩三头日的收尾刺激。',
            keyCues: ['手臂沿斜前方抬成 Y 字轨迹', '用小重量保持肩部控制', '顶端短暂停顿，避免耸肩'],
            commonMistakes: ['甩动身体借力', '抬成普通前平举', '肩膀耸起抢发力'],
            illustration: 'raise',
            imageUrl: '/coach-shots/raise-cue.jpg',
          },
        ],
      },
      {
        id: 'day-2-pull',
        name: 'Day 2 背 / 后束 / 二头',
        focus: ['背', '肩', '二头'],
        sourceUrl: dayTwoSourceUrl,
        exerciseIds: [
          'pull-up',
          'lat-pulldown',
          'barbell-row',
          'seated-cable-row',
          'rear-delt-fly',
          'barbell-curl',
        ],
        coachNotes: [
          {
            exerciseId: 'pull-up',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '先用垂直拉建立背部发力，能做标准动作再追求次数。',
            keyCues: ['先下沉肩胛再屈肘拉起', '胸口主动靠近杠', '下放时保持控制，不要直接掉下去'],
            commonMistakes: ['摆动借力', '只用二头硬拉', '下放不完整'],
            illustration: 'pull',
            imageUrl: '/coach-shots/pull-cue.jpg',
          },
          {
            exerciseId: 'lat-pulldown',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '在更可控的器械里补足背阔肌垂直拉容量。',
            keyCues: ['胸口上挺，肋骨不要乱翻', '肘部向下向后走', '拉到锁骨附近后控制还原'],
            commonMistakes: ['身体后仰过多', '耸肩拉重量', '手腕过度发力'],
            illustration: 'pull',
            imageUrl: '/coach-shots/lat-pulldown-cue.jpg',
          },
          {
            exerciseId: 'barbell-row',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用水平划船增加中背厚度和整体背部张力。',
            keyCues: ['髋部折叠，背部保持中立', '杠铃贴近腿部路径上拉', '肘部向后收，不要只抬手'],
            commonMistakes: ['腰背弯曲', '上半身起伏太大', '拉到胸前过高'],
            illustration: 'row',
            imageUrl: '/coach-shots/row-cue.jpg',
          },
          {
            exerciseId: 'seated-cable-row',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用稳定坐姿继续累积划船容量，减少腰背代偿。',
            keyCues: ['躯干保持稳定', '肩胛向后收再让肘走', '手柄拉向腹部附近'],
            commonMistakes: ['身体前后晃动借力', '耸肩', '只用手臂拉'],
            illustration: 'row',
            imageUrl: '/coach-shots/seated-cable-row-cue.jpg',
          },
          {
            exerciseId: 'rear-delt-fly',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '把后束单独补出来，让拉日不只练背阔和二头。',
            keyCues: ['髋部折叠，躯干稳定', '肘部微屈并向外展开', '用后束带动，不追求大重量'],
            commonMistakes: ['斜方肌代偿', '手臂伸太直', '甩动哑铃'],
            illustration: 'raise',
            imageUrl: '/coach-shots/rear-delt-fly-cue.jpg',
          },
          {
            exerciseId: 'barbell-curl',
            sourceTitle: '凯圣王-谭成义三分化④——跟练背三角肌后束二头',
            sourceUrl: dayTwoSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '在背部训练后直接补二头屈肘力量。',
            keyCues: ['大臂贴近身体', '顶端收缩但不把肘甩到前面', '离心下放保持慢和稳'],
            commonMistakes: ['身体后仰借力', '下放不完整', '手腕乱折'],
            illustration: 'curl',
            imageUrl: '/coach-shots/curl-cue.jpg',
          },
        ],
      },
      {
        id: 'day-3-legs',
        name: 'Day 3 腿部',
        focus: ['腿', '臀'],
        sourceUrl: dayThreeSourceUrl,
        exerciseIds: [
          'squat',
          'leg-press',
          'romanian-deadlift',
          'leg-extension',
          'leg-curl',
          'standing-calf-raise',
        ],
        coachNotes: [
          {
            exerciseId: 'squat',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用深蹲作为腿日主力动作，统一练股四头、臀和核心支撑。',
            keyCues: ['脚掌踩稳，重心压在中足', '膝盖跟随脚尖方向', '下蹲和起身都保持躯干张力'],
            commonMistakes: ['膝盖内扣', '塌腰', '起身时臀部先抬'],
            illustration: 'squat',
            imageUrl: '/coach-shots/squat-cue.jpg',
          },
          {
            exerciseId: 'leg-press',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '在器械里继续堆腿部容量，降低平衡限制。',
            keyCues: ['腰背贴住靠垫', '膝盖沿脚尖方向弯曲', '下放到骨盆仍稳定的深度'],
            commonMistakes: ['臀部卷离靠垫', '膝盖内扣', '顶端锁死膝盖休息'],
            illustration: 'leg-machine',
            imageUrl: '/coach-shots/leg-machine-cue.jpg',
          },
          {
            exerciseId: 'romanian-deadlift',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '把腘绳肌和臀后侧单独拉出来训练。',
            keyCues: ['髋部向后推，不是主动蹲下', '杠铃贴近腿部下放', '感到腘绳肌拉伸后再髋伸站起'],
            commonMistakes: ['膝盖弯曲过多变深蹲', '腰背弯曲', '杠铃离身体太远'],
            illustration: 'hinge',
            imageUrl: '/coach-shots/hinge-cue.jpg',
          },
          {
            exerciseId: 'leg-extension',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '用孤立动作补股四头肌收缩感。',
            keyCues: ['膝关节对准器械轴心', '顶端收缩股四头肌', '下放时别让重量砸回去'],
            commonMistakes: ['重量过大甩动', '坐姿滑动', '顶端不控制'],
            illustration: 'leg-machine',
            imageUrl: '/coach-shots/leg-extension-cue.jpg',
          },
          {
            exerciseId: 'leg-curl',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '补腘绳肌屈膝能力，和罗马尼亚硬拉形成互补。',
            keyCues: ['髋部贴稳垫子', '脚跟向臀部方向卷', '离心下放保持慢'],
            commonMistakes: ['臀部抬起借力', '动作幅度太短', '用惯性甩重量'],
            illustration: 'leg-machine',
            imageUrl: '/coach-shots/leg-curl-cue.jpg',
          },
          {
            exerciseId: 'standing-calf-raise',
            sourceTitle: '凯圣王-谭成义三分化⑤——跟练腿股四头肌腘绳肌',
            sourceUrl: dayThreeSourceUrl,
            sourceBasis: 'B站视频音轨转写整理',
            goal: '在腿日末尾补小腿完整收缩和拉伸。',
            keyCues: ['脚跟充分下放', '顶端踮高后短暂停顿', '全程控制脚踝方向'],
            commonMistakes: ['弹震借力', '幅度太短', '脚踝内外翻'],
            illustration: 'calf',
            imageUrl: '/coach-shots/calf-cue.jpg',
          },
        ],
      },
    ],
  },
  {
    id: 'tanchengyi-private-coaching-follow-along',
    coachName: '谭成义',
    title: '谭成义私教跟练',
    description:
      '按谭成义 B 站私教系列四期公开课（背部/手臂/胸部/肩部）逐字稿整理的四天跟练计划。动作顺序、要领与常见错误均提炼自视频中谭成义的实际讲解，便于对照视频跟练。',
    sourceUrl: privateCoachingBackUrl,
    planType: 'builtin',
days: [
      {
        id: 'private-day-1-back',
        name: 'Day 1 背部',
        focus: ['背', '二头'],
        sourceUrl: privateCoachingBackUrl,
        warmup: [
          { name: '泡沫轴前锯肌推', detail: '跪姿、小臂放泡沫轴上向前推，躯干和重心不动、只动肩，把肩胛骨顶起来激活前锯肌和肩胛稳定。重心越靠前越难，做 2 组。' },
          { name: '健腹轮前推（可选）', detail: '动作模式同上但手参与，能顺带提高手腕和小臂能力；手腕不适的人优先用这个，保持肩胛外展、核心发力。' },
        ],
        exerciseIds: [
          'straight-arm-pulldown',
          'one-arm-cable-row',
          'lat-pulldown',
          'one-arm-lat-pulldown',
          'chest-supported-row',
        ],
        coachNotes: [
          {
            exerciseId: 'straight-arm-pulldown',
            sourceTitle: '谭成义私教系列——保姆级私教视角之背部训练',
            sourceUrl: privateCoachingBackUrl,
            sourceBasis: 'B站谭成义私教背部跟练逐字稿提炼',
            goal: '作为背阔肌主导的开场动作，先把下背阔肌激活起来，背部训练始终以背阔肌为重心。',
            keyCues: ['只微微俯身，身体不要前倾太多', '向下压而不是向后缩（向后缩就没用了）', '可只做半程、感受更好；每次先把背阔肌收紧再做下一次', '刻意深吸一口气，让背预先发力'],
            commonMistakes: ['做成向后划船', '俯身过多换成别的发力', '还原时肩胛松掉、张力丢失'],
            illustration: 'pull',
            imageUrl: '/coach-shots/straight-arm-pulldown-cue.jpg',
          },
          {
            exerciseId: 'one-arm-cable-row',
            sourceTitle: '谭成义私教系列——保姆级私教视角之背部训练',
            sourceUrl: privateCoachingBackUrl,
            sourceBasis: 'B站谭成义私教背部跟练逐字稿提炼',
            goal: '背部第一个正式动作，用单手划船把背阔肌练厚，肩胛和躯干稳定后再做肩的运动。',
            keyCues: ['腿蹬住、稳定骨盆', '另一只手撑住、把身体推向远端找中立位', '微微反手、向后做出尽量大的肩屈幅度', '顶端做一点点小停顿'],
            commonMistakes: ['身体侧屈、旋转借力', '肘往上提、肩胛往里翻', '还原放太多导致张力松掉'],
            illustration: 'row',
            imageUrl: '/coach-shots/one-arm-dumbbell-row-cue.jpg',
          },
          {
            exerciseId: 'lat-pulldown',
            sourceTitle: '谭成义私教系列——保姆级私教视角之背部训练',
            sourceUrl: privateCoachingBackUrl,
            sourceBasis: 'B站谭成义私教背部跟练逐字稿提炼',
            goal: '用对握高位下拉强化背阔肌发力模式，全程控制躯干和肩胛骨位置。',
            keyCues: ['中距对握、带一点点外旋让肘自动往里收', '不要后仰（后仰幅度一大就变成水平划船）', '保持躯干微前倾、避免后仰借力'],
            commonMistakes: ['身体后仰借力变成划船', '外旋过度导致小臂酸', '躯干乱晃、肩胛不稳'],
            illustration: 'pull',
            imageUrl: '/coach-shots/lat-pulldown-cue.jpg',
          },
          {
            exerciseId: 'one-arm-lat-pulldown',
            sourceTitle: '谭成义私教系列——保姆级私教视角之背部训练',
            sourceUrl: privateCoachingBackUrl,
            sourceBasis: 'B站谭成义私教背部跟练逐字稿提炼',
            goal: '背部最后一个正式动作，用单手大肩屈幅度的下压补满背阔肌行程。',
            keyCues: ['手稍微带一点外旋、手腕全程不动', '约20度后仰即可、不要前倾', '深吸气让背预先发力，向下拉而不是向后拉'],
            commonMistakes: ['过度侧屈或旋转', '向后缩变成手臂发力', '手腕乱动、放着放着变成内旋'],
            illustration: 'pull',
            imageUrl: '/coach-shots/one-arm-lat-pulldown-cue.jpg',
          },
          {
            exerciseId: 'chest-supported-row',
            sourceTitle: '谭成义私教系列——保姆级私教视角之背部训练',
            sourceUrl: privateCoachingBackUrl,
            sourceBasis: 'B站谭成义私教背部跟练逐字稿提炼',
            goal: '收尾练中背，用胸支撑姿势把肩胛后缩单独做明白，兼顾菱形肌和中斜方。',
            keyCues: ['胸口贴住靠垫、躯干固定不动', '只做肩胛骨后缩、把幅度做到位', '屁股可往前坐一点找到稳定位'],
            commonMistakes: ['用顶腰代替肩胛后缩', '躯干跟着一起晃', '后缩幅度不足、做得不到位'],
            illustration: 'row',
            imageUrl: '/coach-shots/seated-cable-row-cue.jpg',
          },
        ],
      },
      {
        id: 'private-day-2-arms',
        name: 'Day 2 手臂',
        focus: ['三头', '二头'],
        sourceUrl: privateCoachingArmsUrl,
        warmup: [
          { name: '直接开练 + 热身组', detail: '谭成义原话：手臂训练不需要特别热身，直接开练即可，只需在正式动作前用轻重量多做 1-2 组热身组激活；若三头起步手腕不适，先用更轻的重量多激活几次。' },
        ],
        exerciseIds: [
          'triceps-pushdown',
          'skull-crusher',
          'cable-curl',
          'incline-dumbbell-curl',
          'hammer-curl',
        ],
        coachNotes: [
          {
            exerciseId: 'triceps-pushdown',
            sourceTitle: '谭成义私教系列——第二期手臂教学',
            sourceUrl: privateCoachingArmsUrl,
            sourceBasis: 'B站谭成义私教手臂跟练逐字稿提炼',
            goal: '手臂先练三头：二头先练会充血、影响三头伸展，所以从三头开始，追求肌肉收紧和刻度。',
            keyCues: ['滑轮不要放太高、调低一点避免绳子卡住', '在肩胛骨不动的情况下尽量做大肩屈', '一定要完全伸直锁死、夹肘内收让三头收满', '先把每一个做标准再考虑做几个'],
            commonMistakes: ['用肩膀往下压', '肘往外开、长头松掉', '没完全伸直、只追求个数'],
            illustration: 'bench',
            imageUrl: '/coach-shots/triceps-pushdown-cue.jpg',
          },
          {
            exerciseId: 'skull-crusher',
            sourceTitle: '谭成义私教系列——第二期手臂教学',
            sourceUrl: privateCoachingArmsUrl,
            sourceBasis: 'B站谭成义私教手臂跟练逐字稿提炼',
            goal: '第二个正式动作，用仰卧杠铃臂屈伸给三头增肌，刺激长头。',
            keyCues: ['大臂略向后倾并保持稳定', '下放到额头后侧附近', '伸肘时不要让肩关节大幅摆动'],
            commonMistakes: ['肘部外开', '重量过大砸落', '肩关节代偿过多'],
            illustration: 'bench',
            imageUrl: '/coach-shots/triceps-cue.jpg',
          },
          {
            exerciseId: 'cable-curl',
            sourceTitle: '谭成义私教系列——第二期手臂教学',
            sourceUrl: privateCoachingArmsUrl,
            sourceBasis: 'B站谭成义私教手臂跟练逐字稿提炼',
            goal: '三头练完转二头，用坐姿绳索弯举把大臂固定做出最饱满的二头收缩。',
            keyCues: ['坐姿、大臂压在膝盖上固定不动', '外旋位（小臂靠近尺侧）让二头内侧更饱满', '顶端完全收紧再控制下放'],
            commonMistakes: ['大臂离开支撑点乱晃', '只做半程', '靠惯性甩起重量'],
            illustration: 'curl',
            imageUrl: '/coach-shots/curl-cue.jpg',
          },
          {
            exerciseId: 'incline-dumbbell-curl',
            sourceTitle: '谭成义私教系列——第二期手臂教学',
            sourceUrl: privateCoachingArmsUrl,
            sourceBasis: 'B站谭成义私教手臂跟练逐字稿提炼',
            goal: '在肩屈位拉长二头做离心，用仰卧哑铃弯举补二头的拉伸端刺激。',
            keyCues: ['凳子约45度、肩屈位让二头预先拉长', '保持外旋位、充分拉伸', '下放控制离心、不要让哑铃往前翻导致肩不适'],
            commonMistakes: ['凳子太低导致肩膀不舒服', '下放失控、肩前翻', '没保持外旋、拉伸不充分'],
            illustration: 'curl',
            imageUrl: '/coach-shots/dumbbell-curl-cue.jpg',
          },
          {
            exerciseId: 'hammer-curl',
            sourceTitle: '谭成义私教系列——第二期手臂教学',
            sourceUrl: privateCoachingArmsUrl,
            sourceBasis: 'B站谭成义私教手臂跟练逐字稿提炼',
            goal: '收尾超级组用绳索锤式弯举，主攻上半段顶峰收缩、补肱肌和前臂。',
            keyCues: ['基本只做上半程、下到一半就收紧', '最收紧处停一下做顶峰收缩', '抬的时候大臂不动、不要往后甩'],
            commonMistakes: ['大臂乱动、往后甩借力', '下放过多失去张力', '重量过大耸肩'],
            illustration: 'curl',
            imageUrl: '/coach-shots/hammer-curl-cue.jpg',
          },
        ],
      },
      {
        id: 'private-day-3-chest',
        name: 'Day 3 胸部',
        focus: ['胸', '三头'],
        sourceUrl: privateCoachingChestUrl,
        warmup: [
          { name: '俯卧 TYW（侧重 Y 字）', detail: '泡沫轴垫高、只动肩不动躯干，激活下斜方与肩胛联动。最推荐 Y 字、尽量抬高，胸口抵住泡沫轴吸气做扩张对抗。' },
          { name: '俯卧 Y 字推举', detail: '在胸廓扩张位做 Y 字推举，让肩在更协调的位置上活动，顺带调整肩肱节律。' },
          { name: '弹力带绕肩', detail: '保持弹力带张力，从肩正前方绕到肩正后方，幅度不用大、全程别松掉，给肩关节升温。' },
        ],
        exerciseIds: [
          'parallel-bar-dip',
          'chest-press-machine',
          'incline-dumbbell-press',
          'cable-crossover',
        ],
        coachNotes: [
          {
            exerciseId: 'parallel-bar-dip',
            sourceTitle: '谭成义私教系列——第三期胸部教学',
            sourceUrl: privateCoachingChestUrl,
            sourceBasis: 'B站谭成义私教胸部跟练逐字稿提炼',
            goal: '胸部第一个动作用双杠臂屈伸刺激下胸，练胸的关键是胸廓扩张（挺胸不是挺腰）。',
            keyCues: ['吸满气、保持挺胸（胸廓扩张而非挺腰）', '身体略前倾、肩胛保持稳定', '用胸和三头一起把身体推起'],
            commonMistakes: ['下放过深压肩', '摆动借力', '挺的是腰而不是胸'],
            regression: '做不了完整双杠时，用辅助器械、弹力带或脚支撑退阶。',
            illustration: 'dip',
            imageUrl: '/coach-shots/dip-cue.jpg',
          },
          {
            exerciseId: 'chest-press-machine',
            sourceTitle: '谭成义私教系列——第三期胸部教学',
            sourceUrl: privateCoachingChestUrl,
            sourceBasis: 'B站谭成义私教胸部跟练逐字稿提炼',
            goal: '第二个动作偏中下胸，用器械（或哑铃）推举，配合开肋让下胸更好发力。',
            keyCues: ['半握、靠尺侧让胸的收力更好', '腰贴住、配合开肋扩张前侧', '开肋时保持脊柱位置不变、不要顶腰'],
            commonMistakes: ['全握增大肩关节压力', '顶腰换幅度', '胸部收缩不充分'],
            illustration: 'bench',
            imageUrl: '/coach-shots/bench-cue.jpg',
          },
          {
            exerciseId: 'incline-dumbbell-press',
            sourceTitle: '谭成义私教系列——第三期胸部教学',
            sourceUrl: privateCoachingChestUrl,
            sourceBasis: 'B站谭成义私教胸部跟练逐字稿提炼',
            goal: '用上斜推胸补上胸和锁骨端扩张能力，提升胸肩的立体感。',
            keyCues: ['取后仰极限位（凳子偏平、走上斜轨迹）', '强调上胸和锁骨端的扩张', '保持挺胸、肘部不要过分外开'],
            commonMistakes: ['斜度处理不当变肩推', '下放太浅', '耸肩抢发力'],
            illustration: 'bench',
            imageUrl: '/coach-shots/incline-dumbbell-press-cue.jpg',
          },
          {
            exerciseId: 'cable-crossover',
            sourceTitle: '谭成义私教系列——第三期胸部教学',
            sourceUrl: privateCoachingChestUrl,
            sourceBasis: 'B站谭成义私教胸部跟练逐字稿提炼',
            goal: '收尾用绳索夹上胸保持持续张力，定位在上胸夹胸轨迹。',
            keyCues: ['腰贴住、收着肋、规避下面发力', '往鼻子正前方夹、不要太高（太高到肩）也不要太低（变平夹）', '还原注意肋骨位置、不要为了拉伸把肋骨张太开'],
            commonMistakes: ['借身体摆动', '夹得太高到肩膀', '还原放太多、肋骨张开失控'],
            illustration: 'bench',
            imageUrl: '/coach-shots/cable-crossover-cue.jpg',
          },
        ],
      },
      {
        id: 'private-day-4-shoulders',
        name: 'Day 4 肩部',
        focus: ['肩'],
        sourceUrl: privateCoachingShouldersUrl,
        warmup: [
          { name: '弹力带绕肩', detail: '黄色等较轻弹力带，从肩正前方到肩正后方保持张力做约 20 次，让肩关节升温、分泌滑液，也是一种保养。' },
          { name: 'TRX / 泡沫轴 Y 字提拉', detail: '向头顶方向走出 Y 字、激活肩胛和下斜方；脚越往前越难。没有 TRX 就用胸口抵泡沫轴、只动肩做 Y 字，别顶腰、保持脊柱不动。' },
        ],
        exerciseIds: [
          'rear-delt-fly',
          'reverse-pec-deck',
          'dumbbell-shoulder-press',
          'lateral-raise',
          'front-raise',
        ],
        coachNotes: [
          {
            exerciseId: 'rear-delt-fly',
            sourceTitle: '谭成义私教系列——肩部教学',
            sourceUrl: privateCoachingShouldersUrl,
            sourceBasis: 'B站谭成义私教肩部跟练逐字稿提炼',
            goal: '肩部第一个动作激活后束，用肩屈（而非单纯水平外展）的俯身后束，弱项优先。',
            keyCues: ['轻重量、俯身', '做肩屈的同时肩胛骨不要往前翻、保持下沉', '幅度不要太大、从后束已发力的位置开始'],
            commonMistakes: ['肩胛往前翻、整个肩耸起', '重量过大', '放得太低张力松掉'],
            illustration: 'raise',
            imageUrl: '/coach-shots/rear-delt-fly-cue.jpg',
          },
          {
            exerciseId: 'reverse-pec-deck',
            sourceTitle: '谭成义私教系列——肩部教学',
            sourceUrl: privateCoachingShouldersUrl,
            sourceBasis: 'B站谭成义私教肩部跟练逐字稿提炼',
            goal: '后束正式动作：坐姿反向飞鸟，能上重量、形成大、感受强，是后束效率最高的动作。',
            keyCues: ['座椅调高、让手与肩同高保持稳定', '内旋位让后束更孤立', '兼顾重量、有效幅度和目标肌感受'],
            commonMistakes: ['座椅过低变成上提、稳定性差', '耸肩抢发力', '重量过大失控'],
            illustration: 'raise',
            imageUrl: '/coach-shots/reverse-pec-deck-cue.jpg',
          },
          {
            exerciseId: 'dumbbell-shoulder-press',
            sourceTitle: '谭成义私教系列——肩部教学',
            sourceUrl: privateCoachingShouldersUrl,
            sourceBasis: 'B站谭成义私教肩部跟练逐字稿提炼',
            goal: '用哑铃肩推作为肩部主力推举，肩柔韧性好则凳子可调得更垂直。',
            keyCues: ['凳子调得偏垂直、核心收紧', '腰一定要贴住（不起腰）', '前臂接近垂直、顶端稳定不猛烈碰撞'],
            commonMistakes: ['起腰、腰椎后仰代偿', '耸肩', '下放过快失控'],
            illustration: 'raise',
            imageUrl: '/coach-shots/shoulder-press-cue.jpg',
          },
          {
            exerciseId: 'lateral-raise',
            sourceTitle: '谭成义私教系列——肩部教学',
            sourceUrl: privateCoachingShouldersUrl,
            sourceBasis: 'B站谭成义私教肩部跟练逐字稿提炼',
            goal: '用侧平举练中束，中束无法主动收缩，靠吸满气把动作做完整。',
            keyCues: ['往身体前侧方向抬、中束受力效率更高', '吸满一口气把这一组做完', '可让身体微微前倾'],
            commonMistakes: ['往正侧抬导致中后束松掉', '甩动借力', '手腕明显高于肘'],
            illustration: 'raise',
            imageUrl: '/coach-shots/lateral-raise-cue.jpg',
          },
          {
            exerciseId: 'front-raise',
            sourceTitle: '谭成义私教系列——肩部教学',
            sourceUrl: privateCoachingShouldersUrl,
            sourceBasis: 'B站谭成义私教肩部跟练逐字稿提炼',
            goal: '收尾练前束，用前平举补肩部前侧，注意控制躯干、把节奏做好。',
            keyCues: ['对握、从大腿前方起（别从太低处开始）', '抬到肩高、吸满气', '躯干不晃、不顶腰，下放到碰大腿前侧再抬'],
            commonMistakes: ['起始位太低、前束不发力', '身体摆动借力', '抬得过高、耸肩'],
            illustration: 'raise',
            imageUrl: '/coach-shots/raise-cue.jpg',
          },
        ],
      },
    ],
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return exercises.find((exercise) => exercise.id === id);
}

export function searchExercises(query: string): Exercise[] {
  const normalizedQuery = query.trim().toLowerCase();

  if (!normalizedQuery) {
    return exercises;
  }

  return exercises.filter((exercise) => {
    const searchable = [
      exercise.name,
      exercise.equipment,
      ...exercise.muscleGroups,
      ...exercise.cues,
      ...exercise.commonMistakes,
    ]
      .join(' ')
      .toLowerCase();

    return searchable.includes(normalizedQuery);
  });
}

export type ExerciseFilter = '全部' | MuscleGroup | '手臂';

export function filterExercises(query: string, filter: ExerciseFilter): Exercise[] {
  const results = searchExercises(query);

  if (filter === '全部') {
    return results;
  }

  if (filter === '手臂') {
    return results.filter(
      (exercise) => exercise.muscleGroups.includes('二头') || exercise.muscleGroups.includes('三头'),
    );
  }

  return results.filter((exercise) => exercise.muscleGroups.includes(filter));
}
